# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_rest_health_response import (
    FluidRemoteInternalRestHealthResponse,
)


class TestFluidRemoteInternalRestHealthResponse(unittest.TestCase):
    """FluidRemoteInternalRestHealthResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FluidRemoteInternalRestHealthResponse:
        """Test FluidRemoteInternalRestHealthResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FluidRemoteInternalRestHealthResponse`
        """
        model = FluidRemoteInternalRestHealthResponse()
        if include_optional:
            return FluidRemoteInternalRestHealthResponse(
                status = ''
            )
        else:
            return FluidRemoteInternalRestHealthResponse(
        )
        """

    def testFluidRemoteInternalRestHealthResponse(self):
        """Test FluidRemoteInternalRestHealthResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
