# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_store_change_diff import (
    FluidRemoteInternalStoreChangeDiff,
)


class TestFluidRemoteInternalStoreChangeDiff(unittest.TestCase):
    """FluidRemoteInternalStoreChangeDiff unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FluidRemoteInternalStoreChangeDiff:
        """Test FluidRemoteInternalStoreChangeDiff
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FluidRemoteInternalStoreChangeDiff`
        """
        model = FluidRemoteInternalStoreChangeDiff()
        if include_optional:
            return FluidRemoteInternalStoreChangeDiff(
                commands_run = [
                    virsh_sandbox.models.fluid_remote_internal_store/command_summary.fluid-remote_internal_store.CommandSummary(
                        at = '', 
                        cmd = '', 
                        exit_code = 56, )
                    ],
                files_added = [
                    ''
                    ],
                files_modified = [
                    ''
                    ],
                files_removed = [
                    ''
                    ],
                packages_added = [
                    virsh_sandbox.models.fluid_remote_internal_store/package_info.fluid-remote_internal_store.PackageInfo(
                        name = '', 
                        version = '', )
                    ],
                packages_removed = [
                    virsh_sandbox.models.fluid_remote_internal_store/package_info.fluid-remote_internal_store.PackageInfo(
                        name = '', 
                        version = '', )
                    ],
                services_changed = [
                    virsh_sandbox.models.fluid_remote_internal_store/service_change.fluid-remote_internal_store.ServiceChange(
                        enabled = True, 
                        name = '', 
                        state = '', )
                    ]
            )
        else:
            return FluidRemoteInternalStoreChangeDiff(
        )
        """

    def testFluidRemoteInternalStoreChangeDiff(self):
        """Test FluidRemoteInternalStoreChangeDiff"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
