# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_ansible_job_status import (
    FluidRemoteInternalAnsibleJobStatus,
)


class TestFluidRemoteInternalAnsibleJobStatus(unittest.TestCase):
    """FluidRemoteInternalAnsibleJobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFluidRemoteInternalAnsibleJobStatus(self):
        """Test FluidRemoteInternalAnsibleJobStatus"""
        # inst = FluidRemoteInternalAnsibleJobStatus()


if __name__ == "__main__":
    unittest.main()
