# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_ansible_job_response import (
    FluidRemoteInternalAnsibleJobResponse,
)


class TestFluidRemoteInternalAnsibleJobResponse(unittest.TestCase):
    """FluidRemoteInternalAnsibleJobResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FluidRemoteInternalAnsibleJobResponse:
        """Test FluidRemoteInternalAnsibleJobResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FluidRemoteInternalAnsibleJobResponse`
        """
        model = FluidRemoteInternalAnsibleJobResponse()
        if include_optional:
            return FluidRemoteInternalAnsibleJobResponse(
                job_id = '',
                ws_url = ''
            )
        else:
            return FluidRemoteInternalAnsibleJobResponse(
        )
        """

    def testFluidRemoteInternalAnsibleJobResponse(self):
        """Test FluidRemoteInternalAnsibleJobResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
