# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_rest_session_response import (
    FluidRemoteInternalRestSessionResponse,
)


class TestFluidRemoteInternalRestSessionResponse(unittest.TestCase):
    """FluidRemoteInternalRestSessionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FluidRemoteInternalRestSessionResponse:
        """Test FluidRemoteInternalRestSessionResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FluidRemoteInternalRestSessionResponse`
        """
        model = FluidRemoteInternalRestSessionResponse()
        if include_optional:
            return FluidRemoteInternalRestSessionResponse(
                certificate_id = '',
                duration_seconds = 56,
                ended_at = '',
                id = '',
                sandbox_id = '',
                source_ip = '',
                started_at = '',
                status = '',
                user_id = '',
                vm_id = '',
                vm_ip_address = ''
            )
        else:
            return FluidRemoteInternalRestSessionResponse(
        )
        """

    def testFluidRemoteInternalRestSessionResponse(self):
        """Test FluidRemoteInternalRestSessionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
