# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_store_sandbox_state import (
    FluidRemoteInternalStoreSandboxState,
)


class TestFluidRemoteInternalStoreSandboxState(unittest.TestCase):
    """FluidRemoteInternalStoreSandboxState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFluidRemoteInternalStoreSandboxState(self):
        """Test FluidRemoteInternalStoreSandboxState"""
        # inst = FluidRemoteInternalStoreSandboxState()


if __name__ == "__main__":
    unittest.main()
