# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.api.ansible_playbooks_api import AnsiblePlaybooksApi


class TestAnsiblePlaybooksApi(unittest.TestCase):
    """AnsiblePlaybooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnsiblePlaybooksApi()

    def tearDown(self) -> None:
        pass

    def test_add_playbook_task(self) -> None:
        """Test case for add_playbook_task

        Add task to playbook
        """
        pass

    def test_create_playbook(self) -> None:
        """Test case for create_playbook

        Create playbook
        """
        pass

    def test_delete_playbook(self) -> None:
        """Test case for delete_playbook

        Delete playbook
        """
        pass

    def test_delete_playbook_task(self) -> None:
        """Test case for delete_playbook_task

        Delete task
        """
        pass

    def test_export_playbook(self) -> None:
        """Test case for export_playbook

        Export playbook
        """
        pass

    def test_get_playbook(self) -> None:
        """Test case for get_playbook

        Get playbook
        """
        pass

    def test_list_playbooks(self) -> None:
        """Test case for list_playbooks

        List playbooks
        """
        pass

    def test_reorder_playbook_tasks(self) -> None:
        """Test case for reorder_playbook_tasks

        Reorder tasks
        """
        pass

    def test_update_playbook_task(self) -> None:
        """Test case for update_playbook_task

        Update task
        """
        pass


if __name__ == "__main__":
    unittest.main()
