# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_store_command_exec_record import (
    FluidRemoteInternalStoreCommandExecRecord,
)


class TestFluidRemoteInternalStoreCommandExecRecord(unittest.TestCase):
    """FluidRemoteInternalStoreCommandExecRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> FluidRemoteInternalStoreCommandExecRecord:
        """Test FluidRemoteInternalStoreCommandExecRecord
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FluidRemoteInternalStoreCommandExecRecord`
        """
        model = FluidRemoteInternalStoreCommandExecRecord()
        if include_optional:
            return FluidRemoteInternalStoreCommandExecRecord(
                redacted = {
                    'key' : ''
                    },
                timeout = -9223372036854775808,
                user = '',
                work_dir = ''
            )
        else:
            return FluidRemoteInternalStoreCommandExecRecord(
        )
        """

    def testFluidRemoteInternalStoreCommandExecRecord(self):
        """Test FluidRemoteInternalStoreCommandExecRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
