# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_store_sandbox import (
    FluidRemoteInternalStoreSandbox,
)


class TestFluidRemoteInternalStoreSandbox(unittest.TestCase):
    """FluidRemoteInternalStoreSandbox unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FluidRemoteInternalStoreSandbox:
        """Test FluidRemoteInternalStoreSandbox
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FluidRemoteInternalStoreSandbox`
        """
        model = FluidRemoteInternalStoreSandbox()
        if include_optional:
            return FluidRemoteInternalStoreSandbox(
                agent_id = '',
                base_image = '',
                created_at = '',
                deleted_at = '',
                id = '',
                ip_address = '',
                job_id = '',
                network = '',
                sandbox_name = '',
                state = 'CREATED',
                ttl_seconds = 56,
                updated_at = ''
            )
        else:
            return FluidRemoteInternalStoreSandbox(
        )
        """

    def testFluidRemoteInternalStoreSandbox(self):
        """Test FluidRemoteInternalStoreSandbox"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
