# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_rest_list_sandbox_commands_response import (
    FluidRemoteInternalRestListSandboxCommandsResponse,
)


class TestFluidRemoteInternalRestListSandboxCommandsResponse(unittest.TestCase):
    """FluidRemoteInternalRestListSandboxCommandsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> FluidRemoteInternalRestListSandboxCommandsResponse:
        """Test FluidRemoteInternalRestListSandboxCommandsResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FluidRemoteInternalRestListSandboxCommandsResponse`
        """
        model = FluidRemoteInternalRestListSandboxCommandsResponse()
        if include_optional:
            return FluidRemoteInternalRestListSandboxCommandsResponse(
                commands = [
                    {"metadata":{"redacted":{"key":"redacted"},"work_dir":"work_dir","user":"user","timeout":6},"stdout":"stdout","env_json":"env_json","exit_code":0,"sandbox_id":"sandbox_id","started_at":"started_at","id":"id","stderr":"stderr","command":"command","ended_at":"ended_at"}
                    ],
                total = 56
            )
        else:
            return FluidRemoteInternalRestListSandboxCommandsResponse(
        )
        """

    def testFluidRemoteInternalRestListSandboxCommandsResponse(self):
        """Test FluidRemoteInternalRestListSandboxCommandsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
