# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_rest_run_command_request import (
    FluidRemoteInternalRestRunCommandRequest,
)


class TestFluidRemoteInternalRestRunCommandRequest(unittest.TestCase):
    """FluidRemoteInternalRestRunCommandRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> FluidRemoteInternalRestRunCommandRequest:
        """Test FluidRemoteInternalRestRunCommandRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FluidRemoteInternalRestRunCommandRequest`
        """
        model = FluidRemoteInternalRestRunCommandRequest()
        if include_optional:
            return FluidRemoteInternalRestRunCommandRequest(
                command = '',
                env = {
                    'key' : ''
                    },
                private_key_path = '',
                timeout_sec = 56,
                user = ''
            )
        else:
            return FluidRemoteInternalRestRunCommandRequest(
        )
        """

    def testFluidRemoteInternalRestRunCommandRequest(self):
        """Test FluidRemoteInternalRestRunCommandRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
