# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_rest_list_certificates_response import (
    FluidRemoteInternalRestListCertificatesResponse,
)


class TestFluidRemoteInternalRestListCertificatesResponse(unittest.TestCase):
    """FluidRemoteInternalRestListCertificatesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> FluidRemoteInternalRestListCertificatesResponse:
        """Test FluidRemoteInternalRestListCertificatesResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FluidRemoteInternalRestListCertificatesResponse`
        """
        model = FluidRemoteInternalRestListCertificatesResponse()
        if include_optional:
            return FluidRemoteInternalRestListCertificatesResponse(
                certificates = [
                    virsh_sandbox.models.fluid_remote_internal_rest/certificate_response.fluid-remote_internal_rest.certificateResponse(
                        id = '', 
                        identity = '', 
                        is_expired = True, 
                        issued_at = '', 
                        principals = [
                            ''
                            ], 
                        sandbox_id = '', 
                        serial_number = 56, 
                        status = '', 
                        ttl_seconds = 56, 
                        user_id = '', 
                        valid_after = '', 
                        valid_before = '', 
                        vm_id = '', )
                    ],
                total = 56
            )
        else:
            return FluidRemoteInternalRestListCertificatesResponse(
        )
        """

    def testFluidRemoteInternalRestListCertificatesResponse(self):
        """Test FluidRemoteInternalRestListCertificatesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
