# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_rest_list_vms_response import (
    FluidRemoteInternalRestListVMsResponse,
)


class TestFluidRemoteInternalRestListVMsResponse(unittest.TestCase):
    """FluidRemoteInternalRestListVMsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FluidRemoteInternalRestListVMsResponse:
        """Test FluidRemoteInternalRestListVMsResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FluidRemoteInternalRestListVMsResponse`
        """
        model = FluidRemoteInternalRestListVMsResponse()
        if include_optional:
            return FluidRemoteInternalRestListVMsResponse(
                vms = [
                    {"name":"name","state":"state","persistent":true,"uuid":"uuid","disk_path":"disk_path"}
                    ]
            )
        else:
            return FluidRemoteInternalRestListVMsResponse(
        )
        """

    def testFluidRemoteInternalRestListVMsResponse(self):
        """Test FluidRemoteInternalRestListVMsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
