# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_rest_request_access_response import (
    FluidRemoteInternalRestRequestAccessResponse,
)


class TestFluidRemoteInternalRestRequestAccessResponse(unittest.TestCase):
    """FluidRemoteInternalRestRequestAccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> FluidRemoteInternalRestRequestAccessResponse:
        """Test FluidRemoteInternalRestRequestAccessResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FluidRemoteInternalRestRequestAccessResponse`
        """
        model = FluidRemoteInternalRestRequestAccessResponse()
        if include_optional:
            return FluidRemoteInternalRestRequestAccessResponse(
                certificate = '',
                certificate_id = '',
                connect_command = '',
                instructions = '',
                ssh_port = 56,
                ttl_seconds = 56,
                username = '',
                valid_until = '',
                vm_ip_address = ''
            )
        else:
            return FluidRemoteInternalRestRequestAccessResponse(
        )
        """

    def testFluidRemoteInternalRestRequestAccessResponse(self):
        """Test FluidRemoteInternalRestRequestAccessResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
