# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_ansible_create_playbook_request import (
    FluidRemoteInternalAnsibleCreatePlaybookRequest,
)


class TestFluidRemoteInternalAnsibleCreatePlaybookRequest(unittest.TestCase):
    """FluidRemoteInternalAnsibleCreatePlaybookRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> FluidRemoteInternalAnsibleCreatePlaybookRequest:
        """Test FluidRemoteInternalAnsibleCreatePlaybookRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FluidRemoteInternalAnsibleCreatePlaybookRequest`
        """
        model = FluidRemoteInternalAnsibleCreatePlaybookRequest()
        if include_optional:
            return FluidRemoteInternalAnsibleCreatePlaybookRequest(
                become = True,
                hosts = '',
                name = ''
            )
        else:
            return FluidRemoteInternalAnsibleCreatePlaybookRequest(
        )
        """

    def testFluidRemoteInternalAnsibleCreatePlaybookRequest(self):
        """Test FluidRemoteInternalAnsibleCreatePlaybookRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
