# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_store_playbook_task import (
    FluidRemoteInternalStorePlaybookTask,
)


class TestFluidRemoteInternalStorePlaybookTask(unittest.TestCase):
    """FluidRemoteInternalStorePlaybookTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FluidRemoteInternalStorePlaybookTask:
        """Test FluidRemoteInternalStorePlaybookTask
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FluidRemoteInternalStorePlaybookTask`
        """
        model = FluidRemoteInternalStorePlaybookTask()
        if include_optional:
            return FluidRemoteInternalStorePlaybookTask(
                created_at = '',
                id = '',
                module = '',
                name = '',
                params = None,
                playbook_id = '',
                position = 56
            )
        else:
            return FluidRemoteInternalStorePlaybookTask(
        )
        """

    def testFluidRemoteInternalStorePlaybookTask(self):
        """Test FluidRemoteInternalStorePlaybookTask"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
