# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.internal_rest_list_sandboxes_response import (
    InternalRestListSandboxesResponse,
)


class TestInternalRestListSandboxesResponse(unittest.TestCase):
    """InternalRestListSandboxesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalRestListSandboxesResponse:
        """Test InternalRestListSandboxesResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `InternalRestListSandboxesResponse`
        """
        model = InternalRestListSandboxesResponse()
        if include_optional:
            return InternalRestListSandboxesResponse(
                sandboxes = [
                    virsh_sandbox.models.internal_rest/sandbox_info.internal_rest.sandboxInfo(
                        agent_id = '', 
                        base_image = '', 
                        created_at = '', 
                        id = '', 
                        ip_address = '', 
                        job_id = '', 
                        network = '', 
                        sandbox_name = '', 
                        state = '', 
                        ttl_seconds = 56, 
                        updated_at = '', )
                    ],
                total = 56
            )
        else:
            return InternalRestListSandboxesResponse(
        )
        """

    def testInternalRestListSandboxesResponse(self):
        """Test InternalRestListSandboxesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
