# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_store_playbook import (
    FluidRemoteInternalStorePlaybook,
)


class TestFluidRemoteInternalStorePlaybook(unittest.TestCase):
    """FluidRemoteInternalStorePlaybook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FluidRemoteInternalStorePlaybook:
        """Test FluidRemoteInternalStorePlaybook
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FluidRemoteInternalStorePlaybook`
        """
        model = FluidRemoteInternalStorePlaybook()
        if include_optional:
            return FluidRemoteInternalStorePlaybook(
                become = True,
                created_at = '',
                file_path = '',
                hosts = '',
                id = '',
                name = '',
                updated_at = ''
            )
        else:
            return FluidRemoteInternalStorePlaybook(
        )
        """

    def testFluidRemoteInternalStorePlaybook(self):
        """Test FluidRemoteInternalStorePlaybook"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
