# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_ansible_update_task_request import (
    FluidRemoteInternalAnsibleUpdateTaskRequest,
)


class TestFluidRemoteInternalAnsibleUpdateTaskRequest(unittest.TestCase):
    """FluidRemoteInternalAnsibleUpdateTaskRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> FluidRemoteInternalAnsibleUpdateTaskRequest:
        """Test FluidRemoteInternalAnsibleUpdateTaskRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FluidRemoteInternalAnsibleUpdateTaskRequest`
        """
        model = FluidRemoteInternalAnsibleUpdateTaskRequest()
        if include_optional:
            return FluidRemoteInternalAnsibleUpdateTaskRequest(
                module = '',
                name = '',
                params = None
            )
        else:
            return FluidRemoteInternalAnsibleUpdateTaskRequest(
        )
        """

    def testFluidRemoteInternalAnsibleUpdateTaskRequest(self):
        """Test FluidRemoteInternalAnsibleUpdateTaskRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
