# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.internal_ansible_list_playbooks_response import (
    InternalAnsibleListPlaybooksResponse,
)


class TestInternalAnsibleListPlaybooksResponse(unittest.TestCase):
    """InternalAnsibleListPlaybooksResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalAnsibleListPlaybooksResponse:
        """Test InternalAnsibleListPlaybooksResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `InternalAnsibleListPlaybooksResponse`
        """
        model = InternalAnsibleListPlaybooksResponse()
        if include_optional:
            return InternalAnsibleListPlaybooksResponse(
                playbooks = [
                    {"file_path":"file_path","updated_at":"updated_at","hosts":"hosts","name":"name","created_at":"created_at","id":"id","become":true}
                    ],
                total = 56
            )
        else:
            return InternalAnsibleListPlaybooksResponse(
        )
        """

    def testInternalAnsibleListPlaybooksResponse(self):
        """Test InternalAnsibleListPlaybooksResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
