# coding: utf-8

"""
    fluid-remote API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.fluid_remote_internal_rest_ca_public_key_response import (
    FluidRemoteInternalRestCaPublicKeyResponse,
)


class TestFluidRemoteInternalRestCaPublicKeyResponse(unittest.TestCase):
    """FluidRemoteInternalRestCaPublicKeyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> FluidRemoteInternalRestCaPublicKeyResponse:
        """Test FluidRemoteInternalRestCaPublicKeyResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FluidRemoteInternalRestCaPublicKeyResponse`
        """
        model = FluidRemoteInternalRestCaPublicKeyResponse()
        if include_optional:
            return FluidRemoteInternalRestCaPublicKeyResponse(
                public_key = '',
                usage = ''
            )
        else:
            return FluidRemoteInternalRestCaPublicKeyResponse(
        )
        """

    def testFluidRemoteInternalRestCaPublicKeyResponse(self):
        """Test FluidRemoteInternalRestCaPublicKeyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
