/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for interacting with tmux sessions, panes, and windows
 * OpenAPI spec version: 0.1-beta
 */
import * as zod from 'zod';


/**
 * Get a list of panes in a tmux session
 * @summary List tmux panes
 */
export const getApiV1TmuxPanesQueryParams = zod.object({
  "session": zod.string().optional().describe('Session name')
})

export const getApiV1TmuxPanesResponse = zod.object({
  "panes": zod.array(zod.object({
  "active": zod.boolean().optional(),
  "current_path": zod.string().optional(),
  "pane_height": zod.number().optional(),
  "pane_id": zod.string().optional(),
  "pane_index": zod.number().optional(),
  "pane_pid": zod.number().optional(),
  "pane_title": zod.string().optional(),
  "pane_width": zod.number().optional(),
  "session_name": zod.string().optional(),
  "window_index": zod.number().optional(),
  "window_name": zod.string().optional()
})).optional()
})

/**
 * Kills a tmux pane
 * @summary Kill tmux pane
 */
export const deleteApiV1TmuxPanesPaneIDParams = zod.object({
  "paneID": zod.string().describe('Pane ID')
})

export const deleteApiV1TmuxPanesPaneIDResponse = zod.record(zod.string(), zod.unknown())

/**
 * Creates a new tmux pane
 * @summary Create tmux pane
 */
export const postApiV1TmuxPanesCreateBody = zod.object({
  "command": zod.string().optional(),
  "horizontal": zod.boolean().optional().describe('false = vertical split'),
  "new_window": zod.boolean().optional().describe('true = create new window instead of split'),
  "session_name": zod.string().optional(),
  "window_name": zod.string().optional()
})

export const postApiV1TmuxPanesCreateResponse = zod.object({
  "pane_id": zod.string().optional(),
  "pane_index": zod.number().optional(),
  "session_name": zod.string().optional(),
  "window_index": zod.number().optional()
})

/**
 * Reads the content of a tmux pane
 * @summary Read tmux pane
 */
export const postApiV1TmuxPanesReadBody = zod.object({
  "last_n_lines": zod.number().optional().describe('0 means all visible content'),
  "pane_id": zod.string().optional()
})

export const postApiV1TmuxPanesReadResponse = zod.object({
  "content": zod.string().optional(),
  "lines": zod.number().optional(),
  "pane_id": zod.string().optional()
})

/**
 * Sends keystrokes to a tmux pane
 * @summary Send keys to tmux pane
 */
export const postApiV1TmuxPanesSendKeysBody = zod.object({
  "key": zod.string().optional().describe('Must be from approved list: \"Enter\", \"C-c\", \"C-d\", \"Escape\"'),
  "pane_id": zod.string().optional()
})

export const postApiV1TmuxPanesSendKeysResponse = zod.object({
  "pane_id": zod.string().optional(),
  "sent": zod.boolean().optional()
})

/**
 * Switches to a specific tmux pane
 * @summary Switch tmux pane
 */
export const postApiV1TmuxPanesSwitchBody = zod.object({
  "pane_id": zod.string().optional()
})

export const postApiV1TmuxPanesSwitchResponse = zod.object({
  "pane_id": zod.string().optional(),
  "switched": zod.boolean().optional()
})

/**
 * Get a list of all active tmux sessions
 * @summary List tmux sessions
 */
export const getApiV1TmuxSessionsResponseItem = zod.object({
  "attached": zod.boolean().optional(),
  "created": zod.string().optional(),
  "id": zod.string().optional(),
  "last_pane_x": zod.number().optional(),
  "last_pane_y": zod.number().optional(),
  "name": zod.string().optional(),
  "windows": zod.number().optional()
})
export const getApiV1TmuxSessionsResponse = zod.array(getApiV1TmuxSessionsResponseItem)

/**
 * Releases (kills) a tmux session by ID
 * @summary Release tmux session
 */
export const postApiV1TmuxSessionsSessionIdReleaseParams = zod.object({
  "sessionId": zod.string().describe('Session ID')
})

export const postApiV1TmuxSessionsSessionIdReleaseResponse = zod.object({
  "session_name": zod.string().optional(),
  "success": zod.boolean().optional()
})

/**
 * Kills a tmux session
 * @summary Kill tmux session
 */
export const deleteApiV1TmuxSessionsSessionNameParams = zod.object({
  "sessionName": zod.string().describe('Session name')
})

export const deleteApiV1TmuxSessionsSessionNameResponse = zod.record(zod.string(), zod.unknown())

/**
 * Creates a new tmux session
 * @summary Create tmux session
 */
export const postApiV1TmuxSessionsCreateBody = zod.object({

})

export const postApiV1TmuxSessionsCreateResponse = zod.record(zod.string(), zod.string())

/**
 * Get a list of windows in a tmux session
 * @summary List tmux windows
 */
export const getApiV1TmuxWindowsQueryParams = zod.object({
  "session": zod.string().optional().describe('Session name')
})

export const getApiV1TmuxWindowsResponseItem = zod.object({
  "active": zod.boolean().optional(),
  "height": zod.number().optional(),
  "index": zod.number().optional(),
  "name": zod.string().optional(),
  "panes": zod.number().optional(),
  "session_name": zod.string().optional(),
  "width": zod.number().optional()
})
export const getApiV1TmuxWindowsResponse = zod.array(getApiV1TmuxWindowsResponseItem)

