/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for interacting with tmux sessions, panes, and windows
 * OpenAPI spec version: 0.1-beta
 */
import type { TmuxClientInternalTypesApprovalStatus } from './tmuxClientInternalTypesApprovalStatus';

export interface TmuxClientInternalTypesPendingApproval {
  action_type?: string;
  context?: string;
  created_at?: string;
  expires_at?: string;
  prompt?: string;
  request_id?: string;
  status?: TmuxClientInternalTypesApprovalStatus;
  urgency?: string;
}
