/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for interacting with tmux sessions, panes, and windows
 * OpenAPI spec version: 0.1-beta
 */
import type { TmuxClientInternalTypesAuditEntry } from './tmuxClientInternalTypesAuditEntry';

export interface TmuxClientInternalTypesAuditQueryResponse {
  entries?: TmuxClientInternalTypesAuditEntry[];
  has_more?: boolean;
  total_count?: number;
}
