/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for interacting with tmux sessions, panes, and windows
 * OpenAPI spec version: 0.1-beta
 */
import type { TmuxClientInternalTypesPaneInfo } from './tmuxClientInternalTypesPaneInfo';

export interface TmuxClientInternalTypesListPanesResponse {
  panes?: TmuxClientInternalTypesPaneInfo[];
}
