/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for interacting with tmux sessions, panes, and windows
 * OpenAPI spec version: 0.1-beta
 */

export interface TmuxClientInternalTypesSessionInfo {
  attached?: boolean;
  created?: string;
  id?: string;
  last_pane_x?: number;
  last_pane_y?: number;
  name?: string;
  windows?: number;
}
