/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for interacting with tmux sessions, panes, and windows
 * OpenAPI spec version: 0.1-beta
 */

export interface TmuxClientInternalTypesSendKeysRequest {
  /** Must be from approved list: "Enter", "C-c", "C-d", "Escape" */
  key?: string;
  pane_id?: string;
}
