# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: fluid

before:
  hooks:
    - sh -c "cd fluid-remote && go mod tidy"
    - sh -c "cd fluid && go mod tidy"

builds:
  - id: fluid-remote
    dir: fluid-remote
    main: ./cmd/api/main.go
    binary: fluid-remote
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    tags:
      - libvirt
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}

  - id: fluid
    dir: fluid
    main: ./cmd/fluid
    binary: fluid
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    tags:
      - libvirt
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}

archives:
  - id: fluid-remote
    builds:
      - fluid-remote
    name_template: >-
      fluid-remote_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - LICENSE

  - id: fluid
    builds:
      - fluid
    name_template: >-
      fluid_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: checksums.txt
  algorithm: sha256

signs:
  # Sign binaries
  - id: binary
    cmd: gpg
    artifacts: binary
    signature: "${artifact}.sig"
    args:
      - "--batch"
      - "--yes"
      - "--armor"
      - "--pinentry-mode=loopback"
      - "--passphrase={{ .Env.GPG_PASSPHRASE }}"
      - "--local-user={{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

  # Sign checksums
  - id: checksum
    cmd: gpg
    artifacts: checksum
    signature: "${artifact}.sig"
    args:
      - "--batch"
      - "--yes"
      - "--armor"
      - "--pinentry-mode=loopback"
      - "--passphrase={{ .Env.GPG_PASSPHRASE }}"
      - "--local-user={{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: fluid-remote
    package_name: fluid-remote
    vendor: "Fluid.sh"
    homepage: "https://github.com/aspectrr/fluid.sh"
    maintainer: "Collin Pfeifer <cpfeifer@madcactus.org>"
    description: "Control-plane API for managing libvirt-based VM sandboxes"
    license: "MIT"
    formats:
      - deb
      - rpm
    dependencies:
      - openssh-client
      - postgresql-client
    contents:
      - src: fluid-remote
        dst: /usr/local/bin/fluid-remote

  - id: fluid
    package_name: fluid
    vendor: "Fluid.sh"
    homepage: "https://github.com/aspectrr/fluid.sh"
    maintainer: "Collin Pfeifer <cpfeifer@madcactus.org>"
    description: "CLI for managing fluid sandboxes"
    license: "MIT"
    formats:
      - deb
      - rpm
    contents:
      - src: fluid
        dst: /usr/local/bin/fluid

release:
  github:
    owner: aspectrr
    name: fluid.sh
