# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.tmux_client_internal_api_create_sandbox_session_request import (
    TmuxClientInternalApiCreateSandboxSessionRequest,
)


class TestTmuxClientInternalApiCreateSandboxSessionRequest(unittest.TestCase):
    """TmuxClientInternalApiCreateSandboxSessionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> TmuxClientInternalApiCreateSandboxSessionRequest:
        """Test TmuxClientInternalApiCreateSandboxSessionRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TmuxClientInternalApiCreateSandboxSessionRequest`
        """
        model = TmuxClientInternalApiCreateSandboxSessionRequest()
        if include_optional:
            return TmuxClientInternalApiCreateSandboxSessionRequest(
                sandbox_id = '',
                session_name = '',
                ttl_minutes = 56
            )
        else:
            return TmuxClientInternalApiCreateSandboxSessionRequest(
        )
        """

    def testTmuxClientInternalApiCreateSandboxSessionRequest(self):
        """Test TmuxClientInternalApiCreateSandboxSessionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
