# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest


class TestVirshSandboxInternalAnsibleJobStatus(unittest.TestCase):
    """VirshSandboxInternalAnsibleJobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVirshSandboxInternalAnsibleJobStatus(self):
        """Test VirshSandboxInternalAnsibleJobStatus"""
        # inst = VirshSandboxInternalAnsibleJobStatus()


if __name__ == "__main__":
    unittest.main()
