# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.virsh_sandbox_internal_ansible_list_playbooks_response import (
    VirshSandboxInternalAnsibleListPlaybooksResponse,
)


class TestVirshSandboxInternalAnsibleListPlaybooksResponse(unittest.TestCase):
    """VirshSandboxInternalAnsibleListPlaybooksResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> VirshSandboxInternalAnsibleListPlaybooksResponse:
        """Test VirshSandboxInternalAnsibleListPlaybooksResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `VirshSandboxInternalAnsibleListPlaybooksResponse`
        """
        model = VirshSandboxInternalAnsibleListPlaybooksResponse()
        if include_optional:
            return VirshSandboxInternalAnsibleListPlaybooksResponse(
                playbooks = [
                    {"file_path":"file_path","updated_at":"updated_at","hosts":"hosts","name":"name","created_at":"created_at","id":"id","become":true}
                    ],
                total = 56
            )
        else:
            return VirshSandboxInternalAnsibleListPlaybooksResponse(
        )
        """

    def testVirshSandboxInternalAnsibleListPlaybooksResponse(self):
        """Test VirshSandboxInternalAnsibleListPlaybooksResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
