# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.virsh_sandbox_internal_ansible_add_task_response import (
    VirshSandboxInternalAnsibleAddTaskResponse,
)


class TestVirshSandboxInternalAnsibleAddTaskResponse(unittest.TestCase):
    """VirshSandboxInternalAnsibleAddTaskResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> VirshSandboxInternalAnsibleAddTaskResponse:
        """Test VirshSandboxInternalAnsibleAddTaskResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `VirshSandboxInternalAnsibleAddTaskResponse`
        """
        model = VirshSandboxInternalAnsibleAddTaskResponse()
        if include_optional:
            return VirshSandboxInternalAnsibleAddTaskResponse(
                task = {"module":"module","name":"name","created_at":"created_at","id":"id","position":0,"params":"{}","playbook_id":"playbook_id"}
            )
        else:
            return VirshSandboxInternalAnsibleAddTaskResponse(
        )
        """

    def testVirshSandboxInternalAnsibleAddTaskResponse(self):
        """Test VirshSandboxInternalAnsibleAddTaskResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
