# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.virsh_sandbox_internal_rest_destroy_sandbox_response import (
    VirshSandboxInternalRestDestroySandboxResponse,
)


class TestVirshSandboxInternalRestDestroySandboxResponse(unittest.TestCase):
    """VirshSandboxInternalRestDestroySandboxResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> VirshSandboxInternalRestDestroySandboxResponse:
        """Test VirshSandboxInternalRestDestroySandboxResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `VirshSandboxInternalRestDestroySandboxResponse`
        """
        model = VirshSandboxInternalRestDestroySandboxResponse()
        if include_optional:
            return VirshSandboxInternalRestDestroySandboxResponse(
                base_image = '',
                sandbox_name = '',
                state = 'CREATED',
                ttl_seconds = 56
            )
        else:
            return VirshSandboxInternalRestDestroySandboxResponse(
        )
        """

    def testVirshSandboxInternalRestDestroySandboxResponse(self):
        """Test VirshSandboxInternalRestDestroySandboxResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
