# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.virsh_sandbox_internal_rest_discover_ip_response import (
    VirshSandboxInternalRestDiscoverIPResponse,
)


class TestVirshSandboxInternalRestDiscoverIPResponse(unittest.TestCase):
    """VirshSandboxInternalRestDiscoverIPResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> VirshSandboxInternalRestDiscoverIPResponse:
        """Test VirshSandboxInternalRestDiscoverIPResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `VirshSandboxInternalRestDiscoverIPResponse`
        """
        model = VirshSandboxInternalRestDiscoverIPResponse()
        if include_optional:
            return VirshSandboxInternalRestDiscoverIPResponse(
                ip_address = ''
            )
        else:
            return VirshSandboxInternalRestDiscoverIPResponse(
        )
        """

    def testVirshSandboxInternalRestDiscoverIPResponse(self):
        """Test VirshSandboxInternalRestDiscoverIPResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
