# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.internal_rest_list_sandboxes_response import (
    InternalRestListSandboxesResponse,
)


class TestInternalRestListSandboxesResponse(unittest.TestCase):
    """InternalRestListSandboxesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalRestListSandboxesResponse:
        """Test InternalRestListSandboxesResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `InternalRestListSandboxesResponse`
        """
        model = InternalRestListSandboxesResponse()
        if include_optional:
            return InternalRestListSandboxesResponse(
                sandboxes = [
                    {"base_image":"base_image","agent_id":"agent_id","updated_at":"updated_at","job_id":"job_id","ttl_seconds":0,"created_at":"created_at","sandbox_name":"sandbox_name","id":"id","ip_address":"ip_address","state":"state","network":"network"}
                    ],
                total = 56
            )
        else:
            return InternalRestListSandboxesResponse(
        )
        """

    def testInternalRestListSandboxesResponse(self):
        """Test InternalRestListSandboxesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
