# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.api.access_api import AccessApi


class TestAccessApi(unittest.TestCase):
    """AccessApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccessApi()

    def tearDown(self) -> None:
        pass

    def test_get_ca_public_key(self) -> None:
        """Test case for get_ca_public_key

        Get the SSH CA public key
        """
        pass

    def test_get_certificate(self) -> None:
        """Test case for get_certificate

        Get certificate details
        """
        pass

    def test_list_certificates(self) -> None:
        """Test case for list_certificates

        List certificates
        """
        pass

    def test_list_sessions(self) -> None:
        """Test case for list_sessions

        List sessions
        """
        pass

    def test_record_session_end(self) -> None:
        """Test case for record_session_end

        Record session end
        """
        pass

    def test_record_session_start(self) -> None:
        """Test case for record_session_start

        Record session start
        """
        pass

    def test_request_access(self) -> None:
        """Test case for request_access

        Request SSH access to a sandbox
        """
        pass

    def test_revoke_certificate(self) -> None:
        """Test case for revoke_certificate

        Revoke a certificate
        """
        pass


if __name__ == "__main__":
    unittest.main()
