# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.virsh_sandbox_internal_ansible_reorder_tasks_request import (
    VirshSandboxInternalAnsibleReorderTasksRequest,
)


class TestVirshSandboxInternalAnsibleReorderTasksRequest(unittest.TestCase):
    """VirshSandboxInternalAnsibleReorderTasksRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> VirshSandboxInternalAnsibleReorderTasksRequest:
        """Test VirshSandboxInternalAnsibleReorderTasksRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `VirshSandboxInternalAnsibleReorderTasksRequest`
        """
        model = VirshSandboxInternalAnsibleReorderTasksRequest()
        if include_optional:
            return VirshSandboxInternalAnsibleReorderTasksRequest(
                task_ids = [
                    ''
                    ]
            )
        else:
            return VirshSandboxInternalAnsibleReorderTasksRequest(
        )
        """

    def testVirshSandboxInternalAnsibleReorderTasksRequest(self):
        """Test VirshSandboxInternalAnsibleReorderTasksRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
