# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.internal_rest_session_start_request import (
    InternalRestSessionStartRequest,
)


class TestInternalRestSessionStartRequest(unittest.TestCase):
    """InternalRestSessionStartRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalRestSessionStartRequest:
        """Test InternalRestSessionStartRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `InternalRestSessionStartRequest`
        """
        model = InternalRestSessionStartRequest()
        if include_optional:
            return InternalRestSessionStartRequest(
                certificate_id = '',
                source_ip = ''
            )
        else:
            return InternalRestSessionStartRequest(
        )
        """

    def testInternalRestSessionStartRequest(self):
        """Test InternalRestSessionStartRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
