# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.tmux_client_internal_api_list_sandbox_sessions_response import (
    TmuxClientInternalApiListSandboxSessionsResponse,
)


class TestTmuxClientInternalApiListSandboxSessionsResponse(unittest.TestCase):
    """TmuxClientInternalApiListSandboxSessionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> TmuxClientInternalApiListSandboxSessionsResponse:
        """Test TmuxClientInternalApiListSandboxSessionsResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TmuxClientInternalApiListSandboxSessionsResponse`
        """
        model = TmuxClientInternalApiListSandboxSessionsResponse()
        if include_optional:
            return TmuxClientInternalApiListSandboxSessionsResponse(
                sessions = [
                    {"session_name":"session_name","is_expired":true,"valid_until":"valid_until","sandbox_id":"sandbox_id","ttl_seconds":0,"session_id":"session_id","vm_ip_address":"vm_ip_address","username":"username"}
                    ],
                total = 56
            )
        else:
            return TmuxClientInternalApiListSandboxSessionsResponse(
        )
        """

    def testTmuxClientInternalApiListSandboxSessionsResponse(self):
        """Test TmuxClientInternalApiListSandboxSessionsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
