# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.tmux_client_internal_api_create_sandbox_session_response import (
    TmuxClientInternalApiCreateSandboxSessionResponse,
)


class TestTmuxClientInternalApiCreateSandboxSessionResponse(unittest.TestCase):
    """TmuxClientInternalApiCreateSandboxSessionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> TmuxClientInternalApiCreateSandboxSessionResponse:
        """Test TmuxClientInternalApiCreateSandboxSessionResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TmuxClientInternalApiCreateSandboxSessionResponse`
        """
        model = TmuxClientInternalApiCreateSandboxSessionResponse()
        if include_optional:
            return TmuxClientInternalApiCreateSandboxSessionResponse(
                message = '',
                sandbox_id = '',
                session_id = '',
                session_name = '',
                ttl_seconds = 56,
                username = '',
                valid_until = '',
                vm_ip_address = ''
            )
        else:
            return TmuxClientInternalApiCreateSandboxSessionResponse(
        )
        """

    def testTmuxClientInternalApiCreateSandboxSessionResponse(self):
        """Test TmuxClientInternalApiCreateSandboxSessionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
