# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.virsh_sandbox_internal_ansible_create_playbook_response import (
    VirshSandboxInternalAnsibleCreatePlaybookResponse,
)


class TestVirshSandboxInternalAnsibleCreatePlaybookResponse(unittest.TestCase):
    """VirshSandboxInternalAnsibleCreatePlaybookResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> VirshSandboxInternalAnsibleCreatePlaybookResponse:
        """Test VirshSandboxInternalAnsibleCreatePlaybookResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `VirshSandboxInternalAnsibleCreatePlaybookResponse`
        """
        model = VirshSandboxInternalAnsibleCreatePlaybookResponse()
        if include_optional:
            return VirshSandboxInternalAnsibleCreatePlaybookResponse(
                playbook = {"file_path":"file_path","updated_at":"updated_at","hosts":"hosts","name":"name","created_at":"created_at","id":"id","become":true}
            )
        else:
            return VirshSandboxInternalAnsibleCreatePlaybookResponse(
        )
        """

    def testVirshSandboxInternalAnsibleCreatePlaybookResponse(self):
        """Test VirshSandboxInternalAnsibleCreatePlaybookResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
