# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.internal_rest_list_certificates_response import \
    InternalRestListCertificatesResponse


class TestInternalRestListCertificatesResponse(unittest.TestCase):
    """InternalRestListCertificatesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalRestListCertificatesResponse:
        """Test InternalRestListCertificatesResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `InternalRestListCertificatesResponse`
        """
        model = InternalRestListCertificatesResponse()
        if include_optional:
            return InternalRestListCertificatesResponse(
                certificates = [
                    {"ttl_seconds":6,"principals":["principals","principals"],"serial_number":0,"issued_at":"issued_at","valid_after":"valid_after","vm_id":"vm_id","is_expired":true,"valid_before":"valid_before","user_id":"user_id","identity":"identity","sandbox_id":"sandbox_id","id":"id","status":"status"}
                    ],
                total = 56
            )
        else:
            return InternalRestListCertificatesResponse(
        )
        """

    def testInternalRestListCertificatesResponse(self):
        """Test InternalRestListCertificatesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
