# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest


class TestInternalAnsibleJobStatus(unittest.TestCase):
    """InternalAnsibleJobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInternalAnsibleJobStatus(self):
        """Test InternalAnsibleJobStatus"""
        # inst = InternalAnsibleJobStatus()


if __name__ == "__main__":
    unittest.main()
