# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.internal_rest_request_access_response import \
    InternalRestRequestAccessResponse


class TestInternalRestRequestAccessResponse(unittest.TestCase):
    """InternalRestRequestAccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalRestRequestAccessResponse:
        """Test InternalRestRequestAccessResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `InternalRestRequestAccessResponse`
        """
        model = InternalRestRequestAccessResponse()
        if include_optional:
            return InternalRestRequestAccessResponse(
                certificate = '',
                certificate_id = '',
                connect_command = '',
                instructions = '',
                ssh_port = 56,
                ttl_seconds = 56,
                username = '',
                valid_until = '',
                vm_ip_address = ''
            )
        else:
            return InternalRestRequestAccessResponse(
        )
        """

    def testInternalRestRequestAccessResponse(self):
        """Test InternalRestRequestAccessResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
