/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for interacting with tmux sessions, panes, and windows
 * OpenAPI spec version: 0.1-beta
 */
import * as zod from 'zod';


/**
 * Requests approval from a human for an action
 * @summary Request human approval
 */
export const postApiV1HumanAskBody = zod.object({
  "action_type": zod.string().optional().describe('Category: \"destructive\", \"sensitive\", \"irreversible\"'),
  "alternatives": zod.array(zod.string()).optional().describe('Suggested alternative actions'),
  "context": zod.string().optional().describe('Additional context'),
  "prompt": zod.string().optional().describe('Human-readable description'),
  "timeout_secs": zod.number().optional().describe('Auto-reject after timeout, 0 = no timeout'),
  "urgency": zod.string().optional().describe('\"low\", \"medium\", \"high\"')
})

export const postApiV1HumanAskResponse = zod.object({
  "approved": zod.boolean().optional(),
  "approved_at": zod.string().optional(),
  "approved_by": zod.string().optional(),
  "comment": zod.string().optional(),
  "expires_at": zod.string().optional(),
  "request_id": zod.string().optional(),
  "status": zod.enum(['pending', 'approved', 'rejected', 'expired']).optional()
})

/**
 * Requests approval from a human asynchronously
 * @summary Request human approval asynchronously
 */
export const postApiV1HumanAskAsyncBody = zod.object({
  "action_type": zod.string().optional().describe('Category: \"destructive\", \"sensitive\", \"irreversible\"'),
  "alternatives": zod.array(zod.string()).optional().describe('Suggested alternative actions'),
  "context": zod.string().optional().describe('Additional context'),
  "prompt": zod.string().optional().describe('Human-readable description'),
  "timeout_secs": zod.number().optional().describe('Auto-reject after timeout, 0 = no timeout'),
  "urgency": zod.string().optional().describe('\"low\", \"medium\", \"high\"')
})

export const postApiV1HumanAskAsyncResponse = zod.record(zod.string(), zod.string())

/**
 * Lists all pending human approval requests
 * @summary List pending approvals
 */
export const getApiV1HumanPendingResponse = zod.object({
  "pending": zod.array(zod.object({
  "action_type": zod.string().optional(),
  "context": zod.string().optional(),
  "created_at": zod.string().optional(),
  "expires_at": zod.string().optional(),
  "prompt": zod.string().optional(),
  "request_id": zod.string().optional(),
  "status": zod.enum(['pending', 'approved', 'rejected', 'expired']).optional(),
  "urgency": zod.string().optional()
})).optional()
})

/**
 * Cancels a pending approval request
 * @summary Cancel approval
 */
export const deleteApiV1HumanPendingRequestIDParams = zod.object({
  "requestID": zod.string().describe('Request ID')
})

export const deleteApiV1HumanPendingRequestIDResponse = zod.record(zod.string(), zod.unknown())

/**
 * Retrieves a specific pending approval request
 * @summary Get pending approval
 */
export const getApiV1HumanPendingRequestIDParams = zod.object({
  "requestID": zod.string().describe('Request ID')
})

export const getApiV1HumanPendingRequestIDResponse = zod.object({
  "action_type": zod.string().optional(),
  "context": zod.string().optional(),
  "created_at": zod.string().optional(),
  "expires_at": zod.string().optional(),
  "prompt": zod.string().optional(),
  "request_id": zod.string().optional(),
  "status": zod.enum(['pending', 'approved', 'rejected', 'expired']).optional(),
  "urgency": zod.string().optional()
})

/**
 * Responds to a pending approval request
 * @summary Respond to approval
 */
export const postApiV1HumanRespondBody = zod.object({
  "approved": zod.boolean().optional(),
  "approved_by": zod.string().optional(),
  "comment": zod.string().optional(),
  "request_id": zod.string().optional()
})

export const postApiV1HumanRespondResponse = zod.object({
  "approved": zod.boolean().optional(),
  "approved_at": zod.string().optional(),
  "approved_by": zod.string().optional(),
  "comment": zod.string().optional(),
  "expires_at": zod.string().optional(),
  "request_id": zod.string().optional(),
  "status": zod.enum(['pending', 'approved', 'rejected', 'expired']).optional()
})

