/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for interacting with tmux sessions, panes, and windows
 * OpenAPI spec version: 0.1-beta
 */
import * as zod from 'zod';


/**
 * Queries the audit log for entries
 * @summary Query audit log
 */
export const postApiV1AuditQueryBody = zod.object({
  "action": zod.string().optional(),
  "limit": zod.number().optional(),
  "request_id": zod.string().optional(),
  "since": zod.string().optional(),
  "tool": zod.string().optional(),
  "until": zod.string().optional()
})

export const postApiV1AuditQueryResponse = zod.object({
  "entries": zod.array(zod.object({
  "action": zod.string().optional(),
  "arguments": zod.array(zod.number()).optional(),
  "client_ip": zod.string().optional(),
  "duration_ms": zod.number().optional(),
  "error": zod.object({
  "code": zod.string().optional(),
  "details": zod.string().optional(),
  "message": zod.string().optional()
}).optional(),
  "request_id": zod.string().optional(),
  "result": zod.array(zod.number()).optional(),
  "timestamp": zod.string().optional(),
  "tool": zod.string().optional(),
  "user_agent": zod.string().optional()
})).optional(),
  "has_more": zod.boolean().optional(),
  "total_count": zod.number().optional()
})

/**
 * Retrieves audit log statistics
 * @summary Get audit stats
 */
export const getApiV1AuditStatsResponse = zod.record(zod.string(), zod.unknown())

