/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  GetSandboxParams,
  ListSandboxCommandsParams,
  ListSandboxesParams,
  VirshSandboxInternalRestCreateSandboxRequest,
  VirshSandboxInternalRestCreateSandboxResponse,
  VirshSandboxInternalRestDestroySandboxResponse,
  VirshSandboxInternalRestDiffRequest,
  VirshSandboxInternalRestDiffResponse,
  VirshSandboxInternalRestDiscoverIPResponse,
  VirshSandboxInternalRestErrorResponse,
  VirshSandboxInternalRestGenerateResponse,
  VirshSandboxInternalRestGetSandboxResponse,
  VirshSandboxInternalRestInjectSSHKeyRequest,
  VirshSandboxInternalRestListSandboxCommandsResponse,
  VirshSandboxInternalRestListSandboxesResponse,
  VirshSandboxInternalRestPublishRequest,
  VirshSandboxInternalRestPublishResponse,
  VirshSandboxInternalRestRunCommandRequest,
  VirshSandboxInternalRestRunCommandResponse,
  VirshSandboxInternalRestSnapshotRequest,
  VirshSandboxInternalRestSnapshotResponse,
  VirshSandboxInternalRestStartSandboxRequest,
  VirshSandboxInternalRestStartSandboxResponse,
} from ".././model";

/**
 * Lists all sandboxes with optional filtering by agent_id, job_id, base_image, state, or vm_name
 * @summary List sandboxes
 */
export const listSandboxes = (
  params?: ListSandboxesParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VirshSandboxInternalRestListSandboxesResponse>> => {
  return axios.default.get(`/v1/sandboxes`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getListSandboxesQueryKey = (params?: ListSandboxesParams) => {
  return [`/v1/sandboxes`, ...(params ? [params] : [])] as const;
};

export const getListSandboxesQueryOptions = <
  TData = Awaited<ReturnType<typeof listSandboxes>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  params?: ListSandboxesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listSandboxes>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListSandboxesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listSandboxes>>> = ({
    signal,
  }) => listSandboxes(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listSandboxes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListSandboxesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listSandboxes>>
>;
export type ListSandboxesQueryError =
  AxiosError<VirshSandboxInternalRestErrorResponse>;

export function useListSandboxes<
  TData = Awaited<ReturnType<typeof listSandboxes>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  params: undefined | ListSandboxesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listSandboxes>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSandboxes>>,
          TError,
          Awaited<ReturnType<typeof listSandboxes>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListSandboxes<
  TData = Awaited<ReturnType<typeof listSandboxes>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  params?: ListSandboxesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listSandboxes>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSandboxes>>,
          TError,
          Awaited<ReturnType<typeof listSandboxes>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListSandboxes<
  TData = Awaited<ReturnType<typeof listSandboxes>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  params?: ListSandboxesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listSandboxes>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List sandboxes
 */

export function useListSandboxes<
  TData = Awaited<ReturnType<typeof listSandboxes>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  params?: ListSandboxesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listSandboxes>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListSandboxesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Creates a new virtual machine sandbox by cloning from an existing VM
 * @summary Create a new sandbox
 */
export const createSandbox = (
  virshSandboxInternalRestCreateSandboxRequest: VirshSandboxInternalRestCreateSandboxRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VirshSandboxInternalRestCreateSandboxResponse>> => {
  return axios.default.post(
    `/v1/sandboxes`,
    virshSandboxInternalRestCreateSandboxRequest,
    options,
  );
};

export const getCreateSandboxMutationOptions = <
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSandbox>>,
    TError,
    { data: VirshSandboxInternalRestCreateSandboxRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSandbox>>,
  TError,
  { data: VirshSandboxInternalRestCreateSandboxRequest },
  TContext
> => {
  const mutationKey = ["createSandbox"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSandbox>>,
    { data: VirshSandboxInternalRestCreateSandboxRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createSandbox(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSandboxMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSandbox>>
>;
export type CreateSandboxMutationBody =
  VirshSandboxInternalRestCreateSandboxRequest;
export type CreateSandboxMutationError =
  AxiosError<VirshSandboxInternalRestErrorResponse>;

/**
 * @summary Create a new sandbox
 */
export const useCreateSandbox = <
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSandbox>>,
      TError,
      { data: VirshSandboxInternalRestCreateSandboxRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createSandbox>>,
  TError,
  { data: VirshSandboxInternalRestCreateSandboxRequest },
  TContext
> => {
  const mutationOptions = getCreateSandboxMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Destroys the sandbox and cleans up resources
 * @summary Destroy sandbox
 */
export const destroySandbox = (
  id: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VirshSandboxInternalRestDestroySandboxResponse>> => {
  return axios.default.delete(`/v1/sandboxes/${id}`, options);
};

export const getDestroySandboxMutationOptions = <
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof destroySandbox>>,
    TError,
    { id: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof destroySandbox>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["destroySandbox"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof destroySandbox>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return destroySandbox(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DestroySandboxMutationResult = NonNullable<
  Awaited<ReturnType<typeof destroySandbox>>
>;

export type DestroySandboxMutationError =
  AxiosError<VirshSandboxInternalRestErrorResponse>;

/**
 * @summary Destroy sandbox
 */
export const useDestroySandbox = <
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof destroySandbox>>,
      TError,
      { id: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof destroySandbox>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDestroySandboxMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Returns detailed information about a specific sandbox including recent commands
 * @summary Get sandbox details
 */
export const getSandbox = (
  id: string,
  params?: GetSandboxParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VirshSandboxInternalRestGetSandboxResponse>> => {
  return axios.default.get(`/v1/sandboxes/${id}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetSandboxQueryKey = (
  id?: string,
  params?: GetSandboxParams,
) => {
  return [`/v1/sandboxes/${id}`, ...(params ? [params] : [])] as const;
};

export const getGetSandboxQueryOptions = <
  TData = Awaited<ReturnType<typeof getSandbox>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  id: string,
  params?: GetSandboxParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSandbox>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSandboxQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSandbox>>> = ({
    signal,
  }) => getSandbox(id, params, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getSandbox>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSandboxQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSandbox>>
>;
export type GetSandboxQueryError =
  AxiosError<VirshSandboxInternalRestErrorResponse>;

export function useGetSandbox<
  TData = Awaited<ReturnType<typeof getSandbox>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  id: string,
  params: undefined | GetSandboxParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSandbox>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSandbox>>,
          TError,
          Awaited<ReturnType<typeof getSandbox>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSandbox<
  TData = Awaited<ReturnType<typeof getSandbox>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  id: string,
  params?: GetSandboxParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSandbox>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSandbox>>,
          TError,
          Awaited<ReturnType<typeof getSandbox>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSandbox<
  TData = Awaited<ReturnType<typeof getSandbox>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  id: string,
  params?: GetSandboxParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSandbox>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get sandbox details
 */

export function useGetSandbox<
  TData = Awaited<ReturnType<typeof getSandbox>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  id: string,
  params?: GetSandboxParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSandbox>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetSandboxQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns all commands executed in the sandbox
 * @summary List sandbox commands
 */
export const listSandboxCommands = (
  id: string,
  params?: ListSandboxCommandsParams,
  options?: AxiosRequestConfig,
): Promise<
  AxiosResponse<VirshSandboxInternalRestListSandboxCommandsResponse>
> => {
  return axios.default.get(`/v1/sandboxes/${id}/commands`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getListSandboxCommandsQueryKey = (
  id?: string,
  params?: ListSandboxCommandsParams,
) => {
  return [`/v1/sandboxes/${id}/commands`, ...(params ? [params] : [])] as const;
};

export const getListSandboxCommandsQueryOptions = <
  TData = Awaited<ReturnType<typeof listSandboxCommands>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  id: string,
  params?: ListSandboxCommandsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listSandboxCommands>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListSandboxCommandsQueryKey(id, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listSandboxCommands>>
  > = ({ signal }) =>
    listSandboxCommands(id, params, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listSandboxCommands>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListSandboxCommandsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listSandboxCommands>>
>;
export type ListSandboxCommandsQueryError =
  AxiosError<VirshSandboxInternalRestErrorResponse>;

export function useListSandboxCommands<
  TData = Awaited<ReturnType<typeof listSandboxCommands>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  id: string,
  params: undefined | ListSandboxCommandsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listSandboxCommands>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSandboxCommands>>,
          TError,
          Awaited<ReturnType<typeof listSandboxCommands>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListSandboxCommands<
  TData = Awaited<ReturnType<typeof listSandboxCommands>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  id: string,
  params?: ListSandboxCommandsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listSandboxCommands>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSandboxCommands>>,
          TError,
          Awaited<ReturnType<typeof listSandboxCommands>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListSandboxCommands<
  TData = Awaited<ReturnType<typeof listSandboxCommands>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  id: string,
  params?: ListSandboxCommandsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listSandboxCommands>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List sandbox commands
 */

export function useListSandboxCommands<
  TData = Awaited<ReturnType<typeof listSandboxCommands>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  id: string,
  params?: ListSandboxCommandsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listSandboxCommands>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListSandboxCommandsQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Computes differences between two snapshots
 * @summary Diff snapshots
 */
export const diffSnapshots = (
  id: string,
  virshSandboxInternalRestDiffRequest: VirshSandboxInternalRestDiffRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VirshSandboxInternalRestDiffResponse>> => {
  return axios.default.post(
    `/v1/sandboxes/${id}/diff`,
    virshSandboxInternalRestDiffRequest,
    options,
  );
};

export const getDiffSnapshotsMutationOptions = <
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof diffSnapshots>>,
    TError,
    { id: string; data: VirshSandboxInternalRestDiffRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof diffSnapshots>>,
  TError,
  { id: string; data: VirshSandboxInternalRestDiffRequest },
  TContext
> => {
  const mutationKey = ["diffSnapshots"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof diffSnapshots>>,
    { id: string; data: VirshSandboxInternalRestDiffRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return diffSnapshots(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DiffSnapshotsMutationResult = NonNullable<
  Awaited<ReturnType<typeof diffSnapshots>>
>;
export type DiffSnapshotsMutationBody = VirshSandboxInternalRestDiffRequest;
export type DiffSnapshotsMutationError =
  AxiosError<VirshSandboxInternalRestErrorResponse>;

/**
 * @summary Diff snapshots
 */
export const useDiffSnapshots = <
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof diffSnapshots>>,
      TError,
      { id: string; data: VirshSandboxInternalRestDiffRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof diffSnapshots>>,
  TError,
  { id: string; data: VirshSandboxInternalRestDiffRequest },
  TContext
> => {
  const mutationOptions = getDiffSnapshotsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Generates Ansible or Puppet configuration from sandbox changes
 * @summary Generate configuration
 */
export const generateConfiguration = (
  id: string,
  tool: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.default.post(
    `/v1/sandboxes/${id}/generate/${tool}`,
    undefined,
    options,
  );
};

export const getGenerateConfigurationMutationOptions = <
  TError = AxiosError<
    | VirshSandboxInternalRestErrorResponse
    | VirshSandboxInternalRestGenerateResponse
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateConfiguration>>,
    TError,
    { id: string; tool: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof generateConfiguration>>,
  TError,
  { id: string; tool: string },
  TContext
> => {
  const mutationKey = ["generateConfiguration"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generateConfiguration>>,
    { id: string; tool: string }
  > = (props) => {
    const { id, tool } = props ?? {};

    return generateConfiguration(id, tool, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GenerateConfigurationMutationResult = NonNullable<
  Awaited<ReturnType<typeof generateConfiguration>>
>;

export type GenerateConfigurationMutationError = AxiosError<
  | VirshSandboxInternalRestErrorResponse
  | VirshSandboxInternalRestGenerateResponse
>;

/**
 * @summary Generate configuration
 */
export const useGenerateConfiguration = <
  TError = AxiosError<
    | VirshSandboxInternalRestErrorResponse
    | VirshSandboxInternalRestGenerateResponse
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof generateConfiguration>>,
      TError,
      { id: string; tool: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof generateConfiguration>>,
  TError,
  { id: string; tool: string },
  TContext
> => {
  const mutationOptions = getGenerateConfigurationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Discovers and returns the IP address for a running sandbox. Use this for async workflows where wait_for_ip was false during start.
 * @summary Discover sandbox IP
 */
export const discoverSandboxIP = (
  id: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VirshSandboxInternalRestDiscoverIPResponse>> => {
  return axios.default.get(`/v1/sandboxes/${id}/ip`, options);
};

export const getDiscoverSandboxIPQueryKey = (id?: string) => {
  return [`/v1/sandboxes/${id}/ip`] as const;
};

export const getDiscoverSandboxIPQueryOptions = <
  TData = Awaited<ReturnType<typeof discoverSandboxIP>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof discoverSandboxIP>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDiscoverSandboxIPQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof discoverSandboxIP>>
  > = ({ signal }) => discoverSandboxIP(id, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof discoverSandboxIP>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DiscoverSandboxIPQueryResult = NonNullable<
  Awaited<ReturnType<typeof discoverSandboxIP>>
>;
export type DiscoverSandboxIPQueryError =
  AxiosError<VirshSandboxInternalRestErrorResponse>;

export function useDiscoverSandboxIP<
  TData = Awaited<ReturnType<typeof discoverSandboxIP>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof discoverSandboxIP>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof discoverSandboxIP>>,
          TError,
          Awaited<ReturnType<typeof discoverSandboxIP>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDiscoverSandboxIP<
  TData = Awaited<ReturnType<typeof discoverSandboxIP>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof discoverSandboxIP>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof discoverSandboxIP>>,
          TError,
          Awaited<ReturnType<typeof discoverSandboxIP>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDiscoverSandboxIP<
  TData = Awaited<ReturnType<typeof discoverSandboxIP>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof discoverSandboxIP>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Discover sandbox IP
 */

export function useDiscoverSandboxIP<
  TData = Awaited<ReturnType<typeof discoverSandboxIP>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof discoverSandboxIP>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDiscoverSandboxIPQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Publishes sandbox changes to GitOps repository
 * @summary Publish changes
 */
export const publishChanges = (
  id: string,
  virshSandboxInternalRestPublishRequest: VirshSandboxInternalRestPublishRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.default.post(
    `/v1/sandboxes/${id}/publish`,
    virshSandboxInternalRestPublishRequest,
    options,
  );
};

export const getPublishChangesMutationOptions = <
  TError = AxiosError<
    | VirshSandboxInternalRestErrorResponse
    | VirshSandboxInternalRestPublishResponse
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof publishChanges>>,
    TError,
    { id: string; data: VirshSandboxInternalRestPublishRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof publishChanges>>,
  TError,
  { id: string; data: VirshSandboxInternalRestPublishRequest },
  TContext
> => {
  const mutationKey = ["publishChanges"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof publishChanges>>,
    { id: string; data: VirshSandboxInternalRestPublishRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return publishChanges(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PublishChangesMutationResult = NonNullable<
  Awaited<ReturnType<typeof publishChanges>>
>;
export type PublishChangesMutationBody = VirshSandboxInternalRestPublishRequest;
export type PublishChangesMutationError = AxiosError<
  | VirshSandboxInternalRestErrorResponse
  | VirshSandboxInternalRestPublishResponse
>;

/**
 * @summary Publish changes
 */
export const usePublishChanges = <
  TError = AxiosError<
    | VirshSandboxInternalRestErrorResponse
    | VirshSandboxInternalRestPublishResponse
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof publishChanges>>,
      TError,
      { id: string; data: VirshSandboxInternalRestPublishRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof publishChanges>>,
  TError,
  { id: string; data: VirshSandboxInternalRestPublishRequest },
  TContext
> => {
  const mutationOptions = getPublishChangesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Executes a command inside the sandbox via SSH. If private_key_path is omitted and SSH CA is configured, managed credentials will be used automatically.
 * @summary Run command in sandbox
 */
export const runSandboxCommand = (
  id: string,
  virshSandboxInternalRestRunCommandRequest: VirshSandboxInternalRestRunCommandRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VirshSandboxInternalRestRunCommandResponse>> => {
  return axios.default.post(
    `/v1/sandboxes/${id}/run`,
    virshSandboxInternalRestRunCommandRequest,
    options,
  );
};

export const getRunSandboxCommandMutationOptions = <
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof runSandboxCommand>>,
    TError,
    { id: string; data: VirshSandboxInternalRestRunCommandRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof runSandboxCommand>>,
  TError,
  { id: string; data: VirshSandboxInternalRestRunCommandRequest },
  TContext
> => {
  const mutationKey = ["runSandboxCommand"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof runSandboxCommand>>,
    { id: string; data: VirshSandboxInternalRestRunCommandRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return runSandboxCommand(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RunSandboxCommandMutationResult = NonNullable<
  Awaited<ReturnType<typeof runSandboxCommand>>
>;
export type RunSandboxCommandMutationBody =
  VirshSandboxInternalRestRunCommandRequest;
export type RunSandboxCommandMutationError =
  AxiosError<VirshSandboxInternalRestErrorResponse>;

/**
 * @summary Run command in sandbox
 */
export const useRunSandboxCommand = <
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof runSandboxCommand>>,
      TError,
      { id: string; data: VirshSandboxInternalRestRunCommandRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof runSandboxCommand>>,
  TError,
  { id: string; data: VirshSandboxInternalRestRunCommandRequest },
  TContext
> => {
  const mutationOptions = getRunSandboxCommandMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Creates a snapshot of the sandbox
 * @summary Create snapshot
 */
export const createSnapshot = (
  id: string,
  virshSandboxInternalRestSnapshotRequest: VirshSandboxInternalRestSnapshotRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VirshSandboxInternalRestSnapshotResponse>> => {
  return axios.default.post(
    `/v1/sandboxes/${id}/snapshot`,
    virshSandboxInternalRestSnapshotRequest,
    options,
  );
};

export const getCreateSnapshotMutationOptions = <
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSnapshot>>,
    TError,
    { id: string; data: VirshSandboxInternalRestSnapshotRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSnapshot>>,
  TError,
  { id: string; data: VirshSandboxInternalRestSnapshotRequest },
  TContext
> => {
  const mutationKey = ["createSnapshot"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSnapshot>>,
    { id: string; data: VirshSandboxInternalRestSnapshotRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return createSnapshot(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSnapshotMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSnapshot>>
>;
export type CreateSnapshotMutationBody =
  VirshSandboxInternalRestSnapshotRequest;
export type CreateSnapshotMutationError =
  AxiosError<VirshSandboxInternalRestErrorResponse>;

/**
 * @summary Create snapshot
 */
export const useCreateSnapshot = <
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSnapshot>>,
      TError,
      { id: string; data: VirshSandboxInternalRestSnapshotRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createSnapshot>>,
  TError,
  { id: string; data: VirshSandboxInternalRestSnapshotRequest },
  TContext
> => {
  const mutationOptions = getCreateSnapshotMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Injects a public SSH key for a user in the sandbox
 * @summary Inject SSH key into sandbox
 */
export const injectSshKey = (
  id: string,
  virshSandboxInternalRestInjectSSHKeyRequest: VirshSandboxInternalRestInjectSSHKeyRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.default.post(
    `/v1/sandboxes/${id}/sshkey`,
    virshSandboxInternalRestInjectSSHKeyRequest,
    options,
  );
};

export const getInjectSshKeyMutationOptions = <
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof injectSshKey>>,
    TError,
    { id: string; data: VirshSandboxInternalRestInjectSSHKeyRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof injectSshKey>>,
  TError,
  { id: string; data: VirshSandboxInternalRestInjectSSHKeyRequest },
  TContext
> => {
  const mutationKey = ["injectSshKey"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof injectSshKey>>,
    { id: string; data: VirshSandboxInternalRestInjectSSHKeyRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return injectSshKey(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InjectSshKeyMutationResult = NonNullable<
  Awaited<ReturnType<typeof injectSshKey>>
>;
export type InjectSshKeyMutationBody =
  VirshSandboxInternalRestInjectSSHKeyRequest;
export type InjectSshKeyMutationError =
  AxiosError<VirshSandboxInternalRestErrorResponse>;

/**
 * @summary Inject SSH key into sandbox
 */
export const useInjectSshKey = <
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof injectSshKey>>,
      TError,
      { id: string; data: VirshSandboxInternalRestInjectSSHKeyRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof injectSshKey>>,
  TError,
  { id: string; data: VirshSandboxInternalRestInjectSSHKeyRequest },
  TContext
> => {
  const mutationOptions = getInjectSshKeyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Starts the virtual machine sandbox
 * @summary Start sandbox
 */
export const startSandbox = (
  id: string,
  virshSandboxInternalRestStartSandboxRequest?: VirshSandboxInternalRestStartSandboxRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VirshSandboxInternalRestStartSandboxResponse>> => {
  return axios.default.post(
    `/v1/sandboxes/${id}/start`,
    virshSandboxInternalRestStartSandboxRequest,
    options,
  );
};

export const getStartSandboxMutationOptions = <
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof startSandbox>>,
    TError,
    { id: string; data: VirshSandboxInternalRestStartSandboxRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof startSandbox>>,
  TError,
  { id: string; data: VirshSandboxInternalRestStartSandboxRequest },
  TContext
> => {
  const mutationKey = ["startSandbox"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof startSandbox>>,
    { id: string; data: VirshSandboxInternalRestStartSandboxRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return startSandbox(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StartSandboxMutationResult = NonNullable<
  Awaited<ReturnType<typeof startSandbox>>
>;
export type StartSandboxMutationBody =
  VirshSandboxInternalRestStartSandboxRequest;
export type StartSandboxMutationError =
  AxiosError<VirshSandboxInternalRestErrorResponse>;

/**
 * @summary Start sandbox
 */
export const useStartSandbox = <
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof startSandbox>>,
      TError,
      { id: string; data: VirshSandboxInternalRestStartSandboxRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof startSandbox>>,
  TError,
  { id: string; data: VirshSandboxInternalRestStartSandboxRequest },
  TContext
> => {
  const mutationOptions = getStartSandboxMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Connects via WebSocket to stream realtime sandbox activity (commands, file changes)
 * @summary Stream sandbox activity
 */
export const streamSandboxActivity = (
  id: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.default.get(`/v1/sandboxes/${id}/stream`, options);
};

export const getStreamSandboxActivityQueryKey = (id?: string) => {
  return [`/v1/sandboxes/${id}/stream`] as const;
};

export const getStreamSandboxActivityQueryOptions = <
  TData = Awaited<ReturnType<typeof streamSandboxActivity>>,
  TError = AxiosError<string>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof streamSandboxActivity>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getStreamSandboxActivityQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof streamSandboxActivity>>
  > = ({ signal }) => streamSandboxActivity(id, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof streamSandboxActivity>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StreamSandboxActivityQueryResult = NonNullable<
  Awaited<ReturnType<typeof streamSandboxActivity>>
>;
export type StreamSandboxActivityQueryError = AxiosError<string>;

export function useStreamSandboxActivity<
  TData = Awaited<ReturnType<typeof streamSandboxActivity>>,
  TError = AxiosError<string>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof streamSandboxActivity>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamSandboxActivity>>,
          TError,
          Awaited<ReturnType<typeof streamSandboxActivity>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStreamSandboxActivity<
  TData = Awaited<ReturnType<typeof streamSandboxActivity>>,
  TError = AxiosError<string>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof streamSandboxActivity>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamSandboxActivity>>,
          TError,
          Awaited<ReturnType<typeof streamSandboxActivity>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStreamSandboxActivity<
  TData = Awaited<ReturnType<typeof streamSandboxActivity>>,
  TError = AxiosError<string>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof streamSandboxActivity>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Stream sandbox activity
 */

export function useStreamSandboxActivity<
  TData = Awaited<ReturnType<typeof streamSandboxActivity>>,
  TError = AxiosError<string>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof streamSandboxActivity>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getStreamSandboxActivityQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
