/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  InternalRestCreateSandboxRequest,
  InternalRestCreateSandboxResponse,
  InternalRestDiffRequest,
  InternalRestDiffResponse,
  InternalRestErrorResponse,
  InternalRestGenerateResponse,
  InternalRestInjectSSHKeyRequest,
  InternalRestPublishRequest,
  InternalRestPublishResponse,
  InternalRestRunCommandRequest,
  InternalRestRunCommandResponse,
  InternalRestSnapshotRequest,
  InternalRestSnapshotResponse,
  InternalRestStartSandboxRequest,
  InternalRestStartSandboxResponse,
} from ".././model";

/**
 * Destroys the sandbox and cleans up resources
 * @summary Destroy sandbox
 */
export const destroySandbox = (
  id: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.default.delete(`/v1/sandbox/${id}`, options);
};

export const getDestroySandboxMutationOptions = <
  TError = AxiosError<InternalRestErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof destroySandbox>>,
    TError,
    { id: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof destroySandbox>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["destroySandbox"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof destroySandbox>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return destroySandbox(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DestroySandboxMutationResult = NonNullable<
  Awaited<ReturnType<typeof destroySandbox>>
>;

export type DestroySandboxMutationError = AxiosError<InternalRestErrorResponse>;

/**
 * @summary Destroy sandbox
 */
export const useDestroySandbox = <
  TError = AxiosError<InternalRestErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof destroySandbox>>,
      TError,
      { id: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof destroySandbox>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDestroySandboxMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Computes differences between two snapshots
 * @summary Diff snapshots
 */
export const diffSnapshots = (
  id: string,
  internalRestDiffRequest: InternalRestDiffRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<InternalRestDiffResponse>> => {
  return axios.default.post(
    `/v1/sandbox/${id}/diff`,
    internalRestDiffRequest,
    options,
  );
};

export const getDiffSnapshotsMutationOptions = <
  TError = AxiosError<InternalRestErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof diffSnapshots>>,
    TError,
    { id: string; data: InternalRestDiffRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof diffSnapshots>>,
  TError,
  { id: string; data: InternalRestDiffRequest },
  TContext
> => {
  const mutationKey = ["diffSnapshots"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof diffSnapshots>>,
    { id: string; data: InternalRestDiffRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return diffSnapshots(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DiffSnapshotsMutationResult = NonNullable<
  Awaited<ReturnType<typeof diffSnapshots>>
>;
export type DiffSnapshotsMutationBody = InternalRestDiffRequest;
export type DiffSnapshotsMutationError = AxiosError<InternalRestErrorResponse>;

/**
 * @summary Diff snapshots
 */
export const useDiffSnapshots = <
  TError = AxiosError<InternalRestErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof diffSnapshots>>,
      TError,
      { id: string; data: InternalRestDiffRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof diffSnapshots>>,
  TError,
  { id: string; data: InternalRestDiffRequest },
  TContext
> => {
  const mutationOptions = getDiffSnapshotsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Generates Ansible or Puppet configuration from sandbox changes
 * @summary Generate configuration
 */
export const generateConfiguration = (
  id: string,
  tool: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.default.post(
    `/v1/sandbox/${id}/generate/${tool}`,
    undefined,
    options,
  );
};

export const getGenerateConfigurationMutationOptions = <
  TError = AxiosError<InternalRestErrorResponse | InternalRestGenerateResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateConfiguration>>,
    TError,
    { id: string; tool: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof generateConfiguration>>,
  TError,
  { id: string; tool: string },
  TContext
> => {
  const mutationKey = ["generateConfiguration"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generateConfiguration>>,
    { id: string; tool: string }
  > = (props) => {
    const { id, tool } = props ?? {};

    return generateConfiguration(id, tool, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GenerateConfigurationMutationResult = NonNullable<
  Awaited<ReturnType<typeof generateConfiguration>>
>;

export type GenerateConfigurationMutationError = AxiosError<
  InternalRestErrorResponse | InternalRestGenerateResponse
>;

/**
 * @summary Generate configuration
 */
export const useGenerateConfiguration = <
  TError = AxiosError<InternalRestErrorResponse | InternalRestGenerateResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof generateConfiguration>>,
      TError,
      { id: string; tool: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof generateConfiguration>>,
  TError,
  { id: string; tool: string },
  TContext
> => {
  const mutationOptions = getGenerateConfigurationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Publishes sandbox changes to GitOps repository
 * @summary Publish changes
 */
export const publishChanges = (
  id: string,
  internalRestPublishRequest: InternalRestPublishRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.default.post(
    `/v1/sandbox/${id}/publish`,
    internalRestPublishRequest,
    options,
  );
};

export const getPublishChangesMutationOptions = <
  TError = AxiosError<InternalRestErrorResponse | InternalRestPublishResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof publishChanges>>,
    TError,
    { id: string; data: InternalRestPublishRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof publishChanges>>,
  TError,
  { id: string; data: InternalRestPublishRequest },
  TContext
> => {
  const mutationKey = ["publishChanges"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof publishChanges>>,
    { id: string; data: InternalRestPublishRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return publishChanges(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PublishChangesMutationResult = NonNullable<
  Awaited<ReturnType<typeof publishChanges>>
>;
export type PublishChangesMutationBody = InternalRestPublishRequest;
export type PublishChangesMutationError = AxiosError<
  InternalRestErrorResponse | InternalRestPublishResponse
>;

/**
 * @summary Publish changes
 */
export const usePublishChanges = <
  TError = AxiosError<InternalRestErrorResponse | InternalRestPublishResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof publishChanges>>,
      TError,
      { id: string; data: InternalRestPublishRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof publishChanges>>,
  TError,
  { id: string; data: InternalRestPublishRequest },
  TContext
> => {
  const mutationOptions = getPublishChangesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Executes a command inside the sandbox via SSH
 * @summary Run command in sandbox
 */
export const runSandboxCommand = (
  id: string,
  internalRestRunCommandRequest: InternalRestRunCommandRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<InternalRestRunCommandResponse>> => {
  return axios.default.post(
    `/v1/sandbox/${id}/run`,
    internalRestRunCommandRequest,
    options,
  );
};

export const getRunSandboxCommandMutationOptions = <
  TError = AxiosError<InternalRestErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof runSandboxCommand>>,
    TError,
    { id: string; data: InternalRestRunCommandRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof runSandboxCommand>>,
  TError,
  { id: string; data: InternalRestRunCommandRequest },
  TContext
> => {
  const mutationKey = ["runSandboxCommand"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof runSandboxCommand>>,
    { id: string; data: InternalRestRunCommandRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return runSandboxCommand(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RunSandboxCommandMutationResult = NonNullable<
  Awaited<ReturnType<typeof runSandboxCommand>>
>;
export type RunSandboxCommandMutationBody = InternalRestRunCommandRequest;
export type RunSandboxCommandMutationError =
  AxiosError<InternalRestErrorResponse>;

/**
 * @summary Run command in sandbox
 */
export const useRunSandboxCommand = <
  TError = AxiosError<InternalRestErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof runSandboxCommand>>,
      TError,
      { id: string; data: InternalRestRunCommandRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof runSandboxCommand>>,
  TError,
  { id: string; data: InternalRestRunCommandRequest },
  TContext
> => {
  const mutationOptions = getRunSandboxCommandMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Creates a snapshot of the sandbox
 * @summary Create snapshot
 */
export const createSnapshot = (
  id: string,
  internalRestSnapshotRequest: InternalRestSnapshotRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<InternalRestSnapshotResponse>> => {
  return axios.default.post(
    `/v1/sandbox/${id}/snapshot`,
    internalRestSnapshotRequest,
    options,
  );
};

export const getCreateSnapshotMutationOptions = <
  TError = AxiosError<InternalRestErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSnapshot>>,
    TError,
    { id: string; data: InternalRestSnapshotRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSnapshot>>,
  TError,
  { id: string; data: InternalRestSnapshotRequest },
  TContext
> => {
  const mutationKey = ["createSnapshot"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSnapshot>>,
    { id: string; data: InternalRestSnapshotRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return createSnapshot(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSnapshotMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSnapshot>>
>;
export type CreateSnapshotMutationBody = InternalRestSnapshotRequest;
export type CreateSnapshotMutationError = AxiosError<InternalRestErrorResponse>;

/**
 * @summary Create snapshot
 */
export const useCreateSnapshot = <
  TError = AxiosError<InternalRestErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSnapshot>>,
      TError,
      { id: string; data: InternalRestSnapshotRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createSnapshot>>,
  TError,
  { id: string; data: InternalRestSnapshotRequest },
  TContext
> => {
  const mutationOptions = getCreateSnapshotMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Injects a public SSH key for a user in the sandbox
 * @summary Inject SSH key into sandbox
 */
export const injectSshKey = (
  id: string,
  internalRestInjectSSHKeyRequest: InternalRestInjectSSHKeyRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.default.post(
    `/v1/sandbox/${id}/sshkey`,
    internalRestInjectSSHKeyRequest,
    options,
  );
};

export const getInjectSshKeyMutationOptions = <
  TError = AxiosError<InternalRestErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof injectSshKey>>,
    TError,
    { id: string; data: InternalRestInjectSSHKeyRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof injectSshKey>>,
  TError,
  { id: string; data: InternalRestInjectSSHKeyRequest },
  TContext
> => {
  const mutationKey = ["injectSshKey"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof injectSshKey>>,
    { id: string; data: InternalRestInjectSSHKeyRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return injectSshKey(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InjectSshKeyMutationResult = NonNullable<
  Awaited<ReturnType<typeof injectSshKey>>
>;
export type InjectSshKeyMutationBody = InternalRestInjectSSHKeyRequest;
export type InjectSshKeyMutationError = AxiosError<InternalRestErrorResponse>;

/**
 * @summary Inject SSH key into sandbox
 */
export const useInjectSshKey = <
  TError = AxiosError<InternalRestErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof injectSshKey>>,
      TError,
      { id: string; data: InternalRestInjectSSHKeyRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof injectSshKey>>,
  TError,
  { id: string; data: InternalRestInjectSSHKeyRequest },
  TContext
> => {
  const mutationOptions = getInjectSshKeyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Starts the virtual machine sandbox
 * @summary Start sandbox
 */
export const startSandbox = (
  id: string,
  internalRestStartSandboxRequest?: InternalRestStartSandboxRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<InternalRestStartSandboxResponse>> => {
  return axios.default.post(
    `/v1/sandbox/${id}/start`,
    internalRestStartSandboxRequest,
    options,
  );
};

export const getStartSandboxMutationOptions = <
  TError = AxiosError<InternalRestErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof startSandbox>>,
    TError,
    { id: string; data: InternalRestStartSandboxRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof startSandbox>>,
  TError,
  { id: string; data: InternalRestStartSandboxRequest },
  TContext
> => {
  const mutationKey = ["startSandbox"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof startSandbox>>,
    { id: string; data: InternalRestStartSandboxRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return startSandbox(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StartSandboxMutationResult = NonNullable<
  Awaited<ReturnType<typeof startSandbox>>
>;
export type StartSandboxMutationBody = InternalRestStartSandboxRequest;
export type StartSandboxMutationError = AxiosError<InternalRestErrorResponse>;

/**
 * @summary Start sandbox
 */
export const useStartSandbox = <
  TError = AxiosError<InternalRestErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof startSandbox>>,
      TError,
      { id: string; data: InternalRestStartSandboxRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof startSandbox>>,
  TError,
  { id: string; data: InternalRestStartSandboxRequest },
  TContext
> => {
  const mutationOptions = getStartSandboxMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Creates a new virtual machine sandbox by cloning from an existing VM
 * @summary Create a new sandbox
 */
export const createSandbox = (
  internalRestCreateSandboxRequest: InternalRestCreateSandboxRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<InternalRestCreateSandboxResponse>> => {
  return axios.default.post(
    `/v1/sandbox/create`,
    internalRestCreateSandboxRequest,
    options,
  );
};

export const getCreateSandboxMutationOptions = <
  TError = AxiosError<InternalRestErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSandbox>>,
    TError,
    { data: InternalRestCreateSandboxRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSandbox>>,
  TError,
  { data: InternalRestCreateSandboxRequest },
  TContext
> => {
  const mutationKey = ["createSandbox"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSandbox>>,
    { data: InternalRestCreateSandboxRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createSandbox(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSandboxMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSandbox>>
>;
export type CreateSandboxMutationBody = InternalRestCreateSandboxRequest;
export type CreateSandboxMutationError = AxiosError<InternalRestErrorResponse>;

/**
 * @summary Create a new sandbox
 */
export const useCreateSandbox = <
  TError = AxiosError<InternalRestErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSandbox>>,
      TError,
      { data: InternalRestCreateSandboxRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createSandbox>>,
  TError,
  { data: InternalRestCreateSandboxRequest },
  TContext
> => {
  const mutationOptions = getCreateSandboxMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
