/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  AbortPlan200,
  AbortPlanBody,
  AdvancePlanStep200,
  AdvancePlanStepBody,
  DeletePlan200,
  TmuxClientInternalTypesAPIError,
  TmuxClientInternalTypesCreatePlanRequest,
  TmuxClientInternalTypesCreatePlanResponse,
  TmuxClientInternalTypesGetPlanResponse,
  TmuxClientInternalTypesListPlansResponse,
  TmuxClientInternalTypesUpdatePlanRequest,
  TmuxClientInternalTypesUpdatePlanResponse,
} from ".././model";

/**
 * Lists all execution plans
 * @summary List plans
 */
export const listPlans = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TmuxClientInternalTypesListPlansResponse>> => {
  return axios.default.get(`/v1/plan/`, options);
};

export const getListPlansQueryKey = () => {
  return [`/v1/plan/`] as const;
};

export const getListPlansQueryOptions = <
  TData = Awaited<ReturnType<typeof listPlans>>,
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listPlans>>, TError, TData>
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListPlansQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listPlans>>> = ({
    signal,
  }) => listPlans({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listPlans>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListPlansQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPlans>>
>;
export type ListPlansQueryError = AxiosError<TmuxClientInternalTypesAPIError>;

export function useListPlans<
  TData = Awaited<ReturnType<typeof listPlans>>,
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listPlans>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPlans>>,
          TError,
          Awaited<ReturnType<typeof listPlans>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPlans<
  TData = Awaited<ReturnType<typeof listPlans>>,
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listPlans>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPlans>>,
          TError,
          Awaited<ReturnType<typeof listPlans>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPlans<
  TData = Awaited<ReturnType<typeof listPlans>>,
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listPlans>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List plans
 */

export function useListPlans<
  TData = Awaited<ReturnType<typeof listPlans>>,
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listPlans>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListPlansQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Deletes an execution plan
 * @summary Delete plan
 */
export const deletePlan = (
  planID: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<DeletePlan200>> => {
  return axios.default.delete(`/v1/plan/${planID}`, options);
};

export const getDeletePlanMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePlan>>,
    TError,
    { planID: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePlan>>,
  TError,
  { planID: string },
  TContext
> => {
  const mutationKey = ["deletePlan"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePlan>>,
    { planID: string }
  > = (props) => {
    const { planID } = props ?? {};

    return deletePlan(planID, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePlanMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePlan>>
>;

export type DeletePlanMutationError =
  AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary Delete plan
 */
export const useDeletePlan = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePlan>>,
      TError,
      { planID: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletePlan>>,
  TError,
  { planID: string },
  TContext
> => {
  const mutationOptions = getDeletePlanMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Retrieves a specific execution plan
 * @summary Get plan
 */
export const getPlan = (
  planID: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TmuxClientInternalTypesGetPlanResponse>> => {
  return axios.default.get(`/v1/plan/${planID}`, options);
};

export const getGetPlanQueryKey = (planID?: string) => {
  return [`/v1/plan/${planID}`] as const;
};

export const getGetPlanQueryOptions = <
  TData = Awaited<ReturnType<typeof getPlan>>,
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
>(
  planID: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlan>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPlanQueryKey(planID);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlan>>> = ({
    signal,
  }) => getPlan(planID, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!planID,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getPlan>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetPlanQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPlan>>
>;
export type GetPlanQueryError = AxiosError<TmuxClientInternalTypesAPIError>;

export function useGetPlan<
  TData = Awaited<ReturnType<typeof getPlan>>,
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
>(
  planID: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlan>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlan>>,
          TError,
          Awaited<ReturnType<typeof getPlan>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPlan<
  TData = Awaited<ReturnType<typeof getPlan>>,
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
>(
  planID: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlan>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlan>>,
          TError,
          Awaited<ReturnType<typeof getPlan>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPlan<
  TData = Awaited<ReturnType<typeof getPlan>>,
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
>(
  planID: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlan>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get plan
 */

export function useGetPlan<
  TData = Awaited<ReturnType<typeof getPlan>>,
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
>(
  planID: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlan>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPlanQueryOptions(planID, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Aborts an execution plan
 * @summary Abort plan
 */
export const abortPlan = (
  planID: string,
  abortPlanBody?: AbortPlanBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<AbortPlan200>> => {
  return axios.default.post(`/v1/plan/${planID}/abort`, abortPlanBody, options);
};

export const getAbortPlanMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof abortPlan>>,
    TError,
    { planID: string; data: AbortPlanBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof abortPlan>>,
  TError,
  { planID: string; data: AbortPlanBody },
  TContext
> => {
  const mutationKey = ["abortPlan"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof abortPlan>>,
    { planID: string; data: AbortPlanBody }
  > = (props) => {
    const { planID, data } = props ?? {};

    return abortPlan(planID, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AbortPlanMutationResult = NonNullable<
  Awaited<ReturnType<typeof abortPlan>>
>;
export type AbortPlanMutationBody = AbortPlanBody;
export type AbortPlanMutationError =
  AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary Abort plan
 */
export const useAbortPlan = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof abortPlan>>,
      TError,
      { planID: string; data: AbortPlanBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof abortPlan>>,
  TError,
  { planID: string; data: AbortPlanBody },
  TContext
> => {
  const mutationOptions = getAbortPlanMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Advances to the next step in a plan
 * @summary Advance plan step
 */
export const advancePlanStep = (
  planID: string,
  advancePlanStepBody?: AdvancePlanStepBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<AdvancePlanStep200>> => {
  return axios.default.post(
    `/v1/plan/${planID}/advance`,
    advancePlanStepBody,
    options,
  );
};

export const getAdvancePlanStepMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof advancePlanStep>>,
    TError,
    { planID: string; data: AdvancePlanStepBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof advancePlanStep>>,
  TError,
  { planID: string; data: AdvancePlanStepBody },
  TContext
> => {
  const mutationKey = ["advancePlanStep"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof advancePlanStep>>,
    { planID: string; data: AdvancePlanStepBody }
  > = (props) => {
    const { planID, data } = props ?? {};

    return advancePlanStep(planID, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdvancePlanStepMutationResult = NonNullable<
  Awaited<ReturnType<typeof advancePlanStep>>
>;
export type AdvancePlanStepMutationBody = AdvancePlanStepBody;
export type AdvancePlanStepMutationError =
  AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary Advance plan step
 */
export const useAdvancePlanStep = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof advancePlanStep>>,
      TError,
      { planID: string; data: AdvancePlanStepBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof advancePlanStep>>,
  TError,
  { planID: string; data: AdvancePlanStepBody },
  TContext
> => {
  const mutationOptions = getAdvancePlanStepMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Creates a new execution plan
 * @summary Create plan
 */
export const createPlan = (
  tmuxClientInternalTypesCreatePlanRequest: TmuxClientInternalTypesCreatePlanRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TmuxClientInternalTypesCreatePlanResponse>> => {
  return axios.default.post(
    `/v1/plan/create`,
    tmuxClientInternalTypesCreatePlanRequest,
    options,
  );
};

export const getCreatePlanMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPlan>>,
    TError,
    { data: TmuxClientInternalTypesCreatePlanRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPlan>>,
  TError,
  { data: TmuxClientInternalTypesCreatePlanRequest },
  TContext
> => {
  const mutationKey = ["createPlan"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPlan>>,
    { data: TmuxClientInternalTypesCreatePlanRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createPlan(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePlanMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPlan>>
>;
export type CreatePlanMutationBody = TmuxClientInternalTypesCreatePlanRequest;
export type CreatePlanMutationError =
  AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary Create plan
 */
export const useCreatePlan = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createPlan>>,
      TError,
      { data: TmuxClientInternalTypesCreatePlanRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createPlan>>,
  TError,
  { data: TmuxClientInternalTypesCreatePlanRequest },
  TContext
> => {
  const mutationOptions = getCreatePlanMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Updates an execution plan
 * @summary Update plan
 */
export const updatePlan = (
  tmuxClientInternalTypesUpdatePlanRequest: TmuxClientInternalTypesUpdatePlanRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TmuxClientInternalTypesUpdatePlanResponse>> => {
  return axios.default.post(
    `/v1/plan/update`,
    tmuxClientInternalTypesUpdatePlanRequest,
    options,
  );
};

export const getUpdatePlanMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePlan>>,
    TError,
    { data: TmuxClientInternalTypesUpdatePlanRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updatePlan>>,
  TError,
  { data: TmuxClientInternalTypesUpdatePlanRequest },
  TContext
> => {
  const mutationKey = ["updatePlan"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updatePlan>>,
    { data: TmuxClientInternalTypesUpdatePlanRequest }
  > = (props) => {
    const { data } = props ?? {};

    return updatePlan(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdatePlanMutationResult = NonNullable<
  Awaited<ReturnType<typeof updatePlan>>
>;
export type UpdatePlanMutationBody = TmuxClientInternalTypesUpdatePlanRequest;
export type UpdatePlanMutationError =
  AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary Update plan
 */
export const useUpdatePlan = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updatePlan>>,
      TError,
      { data: TmuxClientInternalTypesUpdatePlanRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updatePlan>>,
  TError,
  { data: TmuxClientInternalTypesUpdatePlanRequest },
  TContext
> => {
  const mutationOptions = getUpdatePlanMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
