/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.1-beta
 */
import * as zod from 'zod';


/**
 * Destroys the sandbox and cleans up resources
 * @summary Destroy sandbox
 */
export const deleteApiV1SandboxIdParams = zod.object({
  "id": zod.string().describe('Sandbox ID')
})

/**
 * Computes differences between two snapshots
 * @summary Diff snapshots
 */
export const postApiV1SandboxIdDiffParams = zod.object({
  "id": zod.string().describe('Sandbox ID')
})

export const postApiV1SandboxIdDiffBody = zod.object({
  "from_snapshot": zod.string().optional().describe('required'),
  "to_snapshot": zod.string().optional().describe('required')
})

export const postApiV1SandboxIdDiffResponse = zod.object({
  "diff": zod.object({
  "created_at": zod.string().optional(),
  "diff_json": zod.object({
  "commands_run": zod.array(zod.object({
  "at": zod.string().optional(),
  "cmd": zod.string().optional(),
  "exit_code": zod.number().optional()
})).optional(),
  "files_added": zod.array(zod.string()).optional(),
  "files_modified": zod.array(zod.string()).optional(),
  "files_removed": zod.array(zod.string()).optional(),
  "packages_added": zod.array(zod.object({
  "name": zod.string().optional(),
  "version": zod.string().optional()
})).optional(),
  "packages_removed": zod.array(zod.object({
  "name": zod.string().optional(),
  "version": zod.string().optional()
})).optional(),
  "services_changed": zod.array(zod.object({
  "enabled": zod.boolean().optional(),
  "name": zod.string().optional(),
  "state": zod.string().optional().describe('started|stopped|restarted|reloaded')
})).optional()
}).optional().describe('JSON-encoded change diff'),
  "from_snapshot": zod.string().optional(),
  "id": zod.string().optional(),
  "sandbox_id": zod.string().optional(),
  "to_snapshot": zod.string().optional()
}).optional()
})

/**
 * Generates Ansible or Puppet configuration from sandbox changes
 * @summary Generate configuration
 */
export const postApiV1SandboxIdGenerateToolParams = zod.object({
  "id": zod.string().describe('Sandbox ID'),
  "tool": zod.string().describe('Tool type (ansible or puppet)')
})

/**
 * Publishes sandbox changes to GitOps repository
 * @summary Publish changes
 */
export const postApiV1SandboxIdPublishParams = zod.object({
  "id": zod.string().describe('Sandbox ID')
})

export const postApiV1SandboxIdPublishBody = zod.object({
  "job_id": zod.string().optional().describe('required'),
  "message": zod.string().optional().describe('optional commit/PR message'),
  "reviewers": zod.array(zod.string()).optional().describe('optional')
})

/**
 * Executes a command inside the sandbox via SSH
 * @summary Run command in sandbox
 */
export const postApiV1SandboxIdRunParams = zod.object({
  "id": zod.string().describe('Sandbox ID')
})

export const postApiV1SandboxIdRunBody = zod.object({
  "command": zod.string().optional().describe('required'),
  "env": zod.record(zod.string(), zod.string()).optional().describe('optional'),
  "private_key_path": zod.string().optional().describe('required; path on API host'),
  "timeout_sec": zod.number().optional().describe('optional; default from service config'),
  "username": zod.string().optional().describe('required')
})

export const postApiV1SandboxIdRunResponse = zod.object({
  "command": zod.object({
  "command": zod.string().optional(),
  "ended_at": zod.string().optional(),
  "env_json": zod.string().optional().describe('JSON-encoded env map'),
  "exit_code": zod.number().optional(),
  "id": zod.string().optional(),
  "metadata": zod.object({
  "redacted": zod.record(zod.string(), zod.string()).optional().describe('placeholders for secrets redaction'),
  "timeout": zod.union([zod.literal(-9223372036854776000),zod.literal(9223372036854776000),zod.literal(1),zod.literal(1000),zod.literal(1000000),zod.literal(1000000000),zod.literal(60000000000),zod.literal(3600000000000)]).optional(),
  "user": zod.string().optional(),
  "work_dir": zod.string().optional()
}).optional(),
  "sandbox_id": zod.string().optional(),
  "started_at": zod.string().optional(),
  "stderr": zod.string().optional(),
  "stdout": zod.string().optional()
}).optional()
})

/**
 * Creates a snapshot of the sandbox
 * @summary Create snapshot
 */
export const postApiV1SandboxIdSnapshotParams = zod.object({
  "id": zod.string().describe('Sandbox ID')
})

export const postApiV1SandboxIdSnapshotBody = zod.object({
  "external": zod.boolean().optional().describe('optional; default false (internal snapshot)'),
  "name": zod.string().optional().describe('required')
})

/**
 * Injects a public SSH key for a user in the sandbox
 * @summary Inject SSH key into sandbox
 */
export const postApiV1SandboxIdSshkeyParams = zod.object({
  "id": zod.string().describe('Sandbox ID')
})

export const postApiV1SandboxIdSshkeyBody = zod.object({
  "public_key": zod.string().optional().describe('required'),
  "username": zod.string().optional().describe('required (explicit); typical: \"ubuntu\" or \"centos\"')
})

/**
 * Starts the virtual machine sandbox
 * @summary Start sandbox
 */
export const postApiV1SandboxIdStartParams = zod.object({
  "id": zod.string().describe('Sandbox ID')
})

export const postApiV1SandboxIdStartBody = zod.object({
  "wait_for_ip": zod.boolean().optional().describe('optional; default false')
})

export const postApiV1SandboxIdStartResponse = zod.object({
  "ip_address": zod.string().optional()
})

/**
 * Creates a new virtual machine sandbox from a base image
 * @summary Create a new sandbox
 */
export const postApiV1SandboxCreateBody = zod.object({
  "agent_id": zod.string().optional().describe('required'),
  "base_image": zod.string().optional().describe('required; e.g. \"ubuntu-22.04.qcow2\"'),
  "cpu": zod.number().optional().describe('optional; default from service config if <=0'),
  "memory_mb": zod.number().optional().describe('optional; default from service config if <=0'),
  "vm_name": zod.string().optional().describe('optional; generated if empty')
})

