/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  VirshSandboxInternalRestErrorResponse,
  VirshSandboxInternalRestListVMsResponse,
} from ".././model";

/**
 * Returns a list of all virtual machines from the libvirt instance
 * @summary List all VMs
 */
export const listVirtualMachines = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<VirshSandboxInternalRestListVMsResponse>> => {
  return axios.default.get(`/v1/vms`, options);
};

export const getListVirtualMachinesQueryKey = () => {
  return [`/v1/vms`] as const;
};

export const getListVirtualMachinesQueryOptions = <
  TData = Awaited<ReturnType<typeof listVirtualMachines>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof listVirtualMachines>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListVirtualMachinesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listVirtualMachines>>
  > = ({ signal }) => listVirtualMachines({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listVirtualMachines>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListVirtualMachinesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listVirtualMachines>>
>;
export type ListVirtualMachinesQueryError =
  AxiosError<VirshSandboxInternalRestErrorResponse>;

export function useListVirtualMachines<
  TData = Awaited<ReturnType<typeof listVirtualMachines>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listVirtualMachines>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVirtualMachines>>,
          TError,
          Awaited<ReturnType<typeof listVirtualMachines>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListVirtualMachines<
  TData = Awaited<ReturnType<typeof listVirtualMachines>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listVirtualMachines>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVirtualMachines>>,
          TError,
          Awaited<ReturnType<typeof listVirtualMachines>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListVirtualMachines<
  TData = Awaited<ReturnType<typeof listVirtualMachines>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listVirtualMachines>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List all VMs
 */

export function useListVirtualMachines<
  TData = Awaited<ReturnType<typeof listVirtualMachines>>,
  TError = AxiosError<VirshSandboxInternalRestErrorResponse>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listVirtualMachines>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListVirtualMachinesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
