/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for interacting with tmux sessions, panes, and windows
 * OpenAPI spec version: 0.1-beta
 */
import * as zod from 'zod';


/**
 * Retrieves the list of allowed and denied commands
 * @summary Get allowed commands
 */
export const getApiV1CommandAllowedResponse = zod.record(zod.string(), zod.unknown())

/**
 * Executes a shell command
 * @summary Run command
 */
export const postApiV1CommandRunBody = zod.object({
  "args": zod.array(zod.string()).optional().describe('Arguments as separate items'),
  "command": zod.string().optional().describe('Executable name only'),
  "dry_run": zod.boolean().optional().describe('If true, don\'t actually run'),
  "env": zod.array(zod.string()).optional().describe('Additional env vars (KEY=VALUE)'),
  "timeout": zod.number().optional().describe('Seconds, 0 = default (30s)'),
  "work_dir": zod.string().optional().describe('Working directory')
})

export const postApiV1CommandRunResponse = zod.object({
  "args": zod.array(zod.string()).optional(),
  "command": zod.string().optional(),
  "dry_run": zod.boolean().optional(),
  "duration_ms": zod.number().optional(),
  "exit_code": zod.number().optional(),
  "stderr": zod.string().optional(),
  "stdout": zod.string().optional(),
  "timed_out": zod.boolean().optional()
})

