/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  GetAllowedCommands200,
  TmuxClientInternalTypesAPIError,
  TmuxClientInternalTypesRunCommandRequest,
  TmuxClientInternalTypesRunCommandResponse,
} from ".././model";

/**
 * Retrieves the list of allowed and denied commands
 * @summary Get allowed commands
 */
export const getAllowedCommands = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetAllowedCommands200>> => {
  return axios.default.get(`/v1/command/allowed`, options);
};

export const getGetAllowedCommandsQueryKey = () => {
  return [`/v1/command/allowed`] as const;
};

export const getGetAllowedCommandsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllowedCommands>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAllowedCommands>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllowedCommandsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllowedCommands>>
  > = ({ signal }) => getAllowedCommands({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllowedCommands>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllowedCommandsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllowedCommands>>
>;
export type GetAllowedCommandsQueryError = AxiosError<unknown>;

export function useGetAllowedCommands<
  TData = Awaited<ReturnType<typeof getAllowedCommands>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllowedCommands>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllowedCommands>>,
          TError,
          Awaited<ReturnType<typeof getAllowedCommands>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllowedCommands<
  TData = Awaited<ReturnType<typeof getAllowedCommands>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllowedCommands>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllowedCommands>>,
          TError,
          Awaited<ReturnType<typeof getAllowedCommands>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllowedCommands<
  TData = Awaited<ReturnType<typeof getAllowedCommands>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllowedCommands>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get allowed commands
 */

export function useGetAllowedCommands<
  TData = Awaited<ReturnType<typeof getAllowedCommands>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllowedCommands>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllowedCommandsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Executes a shell command
 * @summary Run command
 */
export const runCommand = (
  tmuxClientInternalTypesRunCommandRequest: TmuxClientInternalTypesRunCommandRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TmuxClientInternalTypesRunCommandResponse>> => {
  return axios.default.post(
    `/v1/command/run`,
    tmuxClientInternalTypesRunCommandRequest,
    options,
  );
};

export const getRunCommandMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof runCommand>>,
    TError,
    { data: TmuxClientInternalTypesRunCommandRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof runCommand>>,
  TError,
  { data: TmuxClientInternalTypesRunCommandRequest },
  TContext
> => {
  const mutationKey = ["runCommand"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof runCommand>>,
    { data: TmuxClientInternalTypesRunCommandRequest }
  > = (props) => {
    const { data } = props ?? {};

    return runCommand(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RunCommandMutationResult = NonNullable<
  Awaited<ReturnType<typeof runCommand>>
>;
export type RunCommandMutationBody = TmuxClientInternalTypesRunCommandRequest;
export type RunCommandMutationError =
  AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary Run command
 */
export const useRunCommand = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof runCommand>>,
      TError,
      { data: TmuxClientInternalTypesRunCommandRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof runCommand>>,
  TError,
  { data: TmuxClientInternalTypesRunCommandRequest },
  TContext
> => {
  const mutationOptions = getRunCommandMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
