/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */
import type { InternalRestRunCommandRequestEnv } from "./internalRestRunCommandRequestEnv";

export interface InternalRestRunCommandRequest {
  /** required */
  command?: string;
  /** optional */
  env?: InternalRestRunCommandRequestEnv;
  /** optional; if empty, uses managed credentials (requires SSH CA) */
  private_key_path?: string;
  /** optional; default from service config */
  timeout_sec?: number;
  /** optional; defaults to "sandbox" when using managed credentials */
  user?: string;
}
