/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */

export interface InternalRestCertificateResponse {
  id?: string;
  identity?: string;
  is_expired?: boolean;
  issued_at?: string;
  principals?: string[];
  sandbox_id?: string;
  serial_number?: number;
  status?: string;
  ttl_seconds?: number;
  user_id?: string;
  valid_after?: string;
  valid_before?: string;
  vm_id?: string;
}
