/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */

export interface InternalRestRequestAccessResponse {
  /** Certificate is the SSH certificate content (save as key-cert.pub). */
  certificate?: string
  /** CertificateID is the ID of the issued certificate. */
  certificate_id?: string
  /** ConnectCommand is an example SSH command for connecting. */
  connect_command?: string
  /** Instructions provides usage instructions. */
  instructions?: string
  /** SSHPort is the SSH port (usually 22). */
  ssh_port?: number
  /** TTLSeconds is the remaining validity in seconds. */
  ttl_seconds?: number
  /** Username is the SSH username to use. */
  username?: string
  /** ValidUntil is when the certificate expires (RFC3339). */
  valid_until?: string
  /** VMIPAddress is the IP address of the sandbox VM. */
  vm_ip_address?: string
}
