/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */

export interface InternalRestSessionResponse {
  certificate_id?: string;
  duration_seconds?: number;
  ended_at?: string;
  id?: string;
  sandbox_id?: string;
  source_ip?: string;
  started_at?: string;
  status?: string;
  user_id?: string;
  vm_id?: string;
  vm_ip_address?: string;
}
