/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */

export interface InternalRestSandboxInfo {
  agent_id?: string;
  base_image?: string;
  created_at?: string;
  id?: string;
  ip_address?: string;
  job_id?: string;
  network?: string;
  sandbox_name?: string;
  state?: string;
  ttl_seconds?: number;
  updated_at?: string;
}
