/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */

export interface InternalRestRequestAccessRequest {
  /** PublicKey is the user's SSH public key in OpenSSH format. */
  public_key?: string;
  /** SandboxID is the target sandbox. */
  sandbox_id?: string;
  /** TTLMinutes is the requested access duration (1-10 minutes). */
  ttl_minutes?: number;
  /** UserID identifies the requesting user. */
  user_id?: string;
}
