/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */

export interface InternalRestCaPublicKeyResponse {
  /** PublicKey is the CA public key in OpenSSH format. */
  public_key?: string;
  /** Usage explains how to use this key. */
  usage?: string;
}
