/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */

export type ListSandboxesParams = {
/**
 * Filter by agent ID
 */
agent_id?: string;
/**
 * Filter by job ID
 */
job_id?: string;
/**
 * Filter by base image
 */
base_image?: string;
/**
 * Filter by state (CREATED, STARTING, RUNNING, STOPPED, DESTROYED, ERROR)
 */
state?: string;
/**
 * Filter by VM name
 */
vm_name?: string;
/**
 * Max results to return
 */
limit?: number;
/**
 * Number of results to skip
 */
offset?: number;
};
