/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */

export type ListCertificatesParams = {
  /**
   * Filter by sandbox ID
   */
  sandbox_id?: string
  /**
   * Filter by user ID
   */
  user_id?: string
  /**
   * Filter by status (ACTIVE, EXPIRED, REVOKED)
   */
  status?: string
  /**
   * Only show active, non-expired certificates
   */
  active_only?: boolean
  /**
   * Maximum results to return
   */
  limit?: number
  /**
   * Offset for pagination
   */
  offset?: number
}
