/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */
import type { VirshSandboxInternalRestRunCommandRequestEnv } from './virshSandboxInternalRestRunCommandRequestEnv'

export interface VirshSandboxInternalRestRunCommandRequest {
  /** required */
  command?: string
  /** optional */
  env?: VirshSandboxInternalRestRunCommandRequestEnv
  /** optional; if empty, uses managed credentials (requires SSH CA) */
  private_key_path?: string
  /** optional; default from service config */
  timeout_sec?: number
  /** optional; defaults to "sandbox" when using managed credentials */
  user?: string
}
