/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */

export interface VirshSandboxInternalStorePlaybook {
  /** whether to use privilege escalation */
  become?: boolean
  created_at?: string
  /** rendered YAML file path */
  file_path?: string
  /** target hosts pattern (e.g., "all", "webservers") */
  hosts?: string
  id?: string
  /** unique playbook name */
  name?: string
  updated_at?: string
}
