/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * virsh-sandbox API
 * API for managing virtual machine sandboxes using libvirt
 * OpenAPI spec version: 0.0.1-beta
 */

export interface VirshSandboxInternalRestCreateSandboxRequest {
  /** required */
  agent_id?: string;
  /** optional; if true, start the VM immediately after creation */
  auto_start?: boolean;
  /** optional; default from service config if <=0 */
  cpu?: number;
  /** optional; default from service config if <=0 */
  memory_mb?: number;
  /** required; name of existing VM in libvirt to clone from */
  source_vm_name?: string;
  /** optional; TTL for auto garbage collection */
  ttl_seconds?: number;
  /** optional; generated if empty */
  vm_name?: string;
  /** optional; if true and auto_start, wait for IP discovery */
  wait_for_ip?: boolean;
}
