/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for interacting with tmux sessions, panes, and windows
 * OpenAPI spec version: 0.1-beta
 */
import * as zod from 'zod';


/**
 * Copies a file from source to destination
 * @summary Copy file
 */
export const postApiV1FileCopyBody = zod.object({
  "destination": zod.string().optional(),
  "overwrite": zod.boolean().optional(),
  "source": zod.string().optional()
})

export const postApiV1FileCopyResponse = zod.object({
  "bytes_copied": zod.number().optional(),
  "copied": zod.boolean().optional(),
  "destination": zod.string().optional(),
  "source": zod.string().optional()
})

/**
 * Deletes a file or directory
 * @summary Delete file
 */
export const postApiV1FileDeleteBody = zod.object({
  "path": zod.string().optional(),
  "recursive": zod.boolean().optional().describe('For directories')
})

export const postApiV1FileDeleteResponse = zod.object({
  "deleted": zod.boolean().optional(),
  "path": zod.string().optional(),
  "was_dir": zod.boolean().optional()
})

/**
 * Edits the content of a file
 * @summary Edit file
 */
export const postApiV1FileEditBody = zod.object({
  "all": zod.boolean().optional().describe('Replace all occurrences (default: first only)'),
  "new_text": zod.string().optional().describe('Replacement text'),
  "old_text": zod.string().optional().describe('Text to find and replace'),
  "path": zod.string().optional()
})

export const postApiV1FileEditResponse = zod.object({
  "content_after": zod.string().optional().describe('For audit trail'),
  "content_before": zod.string().optional().describe('For audit trail'),
  "diff": zod.string().optional().describe('Unified diff format'),
  "edited": zod.boolean().optional(),
  "path": zod.string().optional(),
  "replacements": zod.number().optional()
})

/**
 * Checks if a file or directory exists
 * @summary Check if file exists
 */
export const postApiV1FileExistsBody = zod.object({

})

export const postApiV1FileExistsResponse = zod.record(zod.string(), zod.unknown())

/**
 * Computes the SHA256 hash of a file
 * @summary Get file hash
 */
export const postApiV1FileHashBody = zod.object({

})

export const postApiV1FileHashResponse = zod.record(zod.string(), zod.string())

/**
 * Lists the contents of a directory
 * @summary List directory contents
 */
export const postApiV1FileListBody = zod.object({
  "max_depth": zod.number().optional(),
  "path": zod.string().optional(),
  "recursive": zod.boolean().optional()
})

export const postApiV1FileListResponse = zod.object({
  "files": zod.array(zod.object({
  "is_dir": zod.boolean().optional(),
  "mod_time": zod.string().optional(),
  "mode": zod.string().optional(),
  "name": zod.string().optional(),
  "path": zod.string().optional(),
  "size": zod.number().optional()
})).optional(),
  "path": zod.string().optional()
})

/**
 * Reads the content of a file
 * @summary Read file
 */
export const postApiV1FileReadBody = zod.object({
  "from_line": zod.number().optional().describe('1-indexed, 0 = start'),
  "max_lines": zod.number().optional().describe('0 = no limit'),
  "path": zod.string().optional(),
  "to_line": zod.number().optional().describe('1-indexed, 0 = end')
})

export const postApiV1FileReadResponse = zod.object({
  "content": zod.string().optional(),
  "from_line": zod.number().optional(),
  "mod_time": zod.string().optional(),
  "mode": zod.string().optional(),
  "path": zod.string().optional(),
  "size": zod.number().optional(),
  "to_line": zod.number().optional(),
  "total_lines": zod.number().optional(),
  "truncated": zod.boolean().optional()
})

/**
 * Writes content to a file
 * @summary Write file
 */
export const postApiV1FileWriteBody = zod.object({
  "content": zod.string().optional(),
  "create_dir": zod.boolean().optional().describe('Create parent directories if needed'),
  "mode": zod.string().optional().describe('e.g., \"0644\"'),
  "overwrite": zod.boolean().optional().describe('Must be true to overwrite existing'),
  "path": zod.string().optional()
})

export const postApiV1FileWriteResponse = zod.object({
  "bytes_written": zod.number().optional(),
  "created": zod.boolean().optional().describe('true if file was created, false if overwritten'),
  "path": zod.string().optional(),
  "written": zod.boolean().optional()
})

