/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  AskHumanAsync200,
  CancelApproval200,
  TmuxClientInternalTypesAPIError,
  TmuxClientInternalTypesApproveRequest,
  TmuxClientInternalTypesAskHumanRequest,
  TmuxClientInternalTypesAskHumanResponse,
  TmuxClientInternalTypesListApprovalsResponse,
  TmuxClientInternalTypesPendingApproval,
} from ".././model";

/**
 * Requests approval from a human for an action
 * @summary Request human approval
 */
export const askHuman = (
  tmuxClientInternalTypesAskHumanRequest: TmuxClientInternalTypesAskHumanRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TmuxClientInternalTypesAskHumanResponse>> => {
  return axios.default.post(
    `/v1/human/ask`,
    tmuxClientInternalTypesAskHumanRequest,
    options,
  );
};

export const getAskHumanMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof askHuman>>,
    TError,
    { data: TmuxClientInternalTypesAskHumanRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof askHuman>>,
  TError,
  { data: TmuxClientInternalTypesAskHumanRequest },
  TContext
> => {
  const mutationKey = ["askHuman"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof askHuman>>,
    { data: TmuxClientInternalTypesAskHumanRequest }
  > = (props) => {
    const { data } = props ?? {};

    return askHuman(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AskHumanMutationResult = NonNullable<
  Awaited<ReturnType<typeof askHuman>>
>;
export type AskHumanMutationBody = TmuxClientInternalTypesAskHumanRequest;
export type AskHumanMutationError = AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary Request human approval
 */
export const useAskHuman = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof askHuman>>,
      TError,
      { data: TmuxClientInternalTypesAskHumanRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof askHuman>>,
  TError,
  { data: TmuxClientInternalTypesAskHumanRequest },
  TContext
> => {
  const mutationOptions = getAskHumanMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Requests approval from a human asynchronously
 * @summary Request human approval asynchronously
 */
export const askHumanAsync = (
  tmuxClientInternalTypesAskHumanRequest: TmuxClientInternalTypesAskHumanRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<AskHumanAsync200>> => {
  return axios.default.post(
    `/v1/human/ask-async`,
    tmuxClientInternalTypesAskHumanRequest,
    options,
  );
};

export const getAskHumanAsyncMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof askHumanAsync>>,
    TError,
    { data: TmuxClientInternalTypesAskHumanRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof askHumanAsync>>,
  TError,
  { data: TmuxClientInternalTypesAskHumanRequest },
  TContext
> => {
  const mutationKey = ["askHumanAsync"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof askHumanAsync>>,
    { data: TmuxClientInternalTypesAskHumanRequest }
  > = (props) => {
    const { data } = props ?? {};

    return askHumanAsync(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AskHumanAsyncMutationResult = NonNullable<
  Awaited<ReturnType<typeof askHumanAsync>>
>;
export type AskHumanAsyncMutationBody = TmuxClientInternalTypesAskHumanRequest;
export type AskHumanAsyncMutationError =
  AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary Request human approval asynchronously
 */
export const useAskHumanAsync = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof askHumanAsync>>,
      TError,
      { data: TmuxClientInternalTypesAskHumanRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof askHumanAsync>>,
  TError,
  { data: TmuxClientInternalTypesAskHumanRequest },
  TContext
> => {
  const mutationOptions = getAskHumanAsyncMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Lists all pending human approval requests
 * @summary List pending approvals
 */
export const listPendingApprovals = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TmuxClientInternalTypesListApprovalsResponse>> => {
  return axios.default.get(`/v1/human/pending`, options);
};

export const getListPendingApprovalsQueryKey = () => {
  return [`/v1/human/pending`] as const;
};

export const getListPendingApprovalsQueryOptions = <
  TData = Awaited<ReturnType<typeof listPendingApprovals>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof listPendingApprovals>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListPendingApprovalsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listPendingApprovals>>
  > = ({ signal }) => listPendingApprovals({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listPendingApprovals>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListPendingApprovalsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPendingApprovals>>
>;
export type ListPendingApprovalsQueryError = AxiosError<unknown>;

export function useListPendingApprovals<
  TData = Awaited<ReturnType<typeof listPendingApprovals>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPendingApprovals>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPendingApprovals>>,
          TError,
          Awaited<ReturnType<typeof listPendingApprovals>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPendingApprovals<
  TData = Awaited<ReturnType<typeof listPendingApprovals>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPendingApprovals>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPendingApprovals>>,
          TError,
          Awaited<ReturnType<typeof listPendingApprovals>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPendingApprovals<
  TData = Awaited<ReturnType<typeof listPendingApprovals>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPendingApprovals>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List pending approvals
 */

export function useListPendingApprovals<
  TData = Awaited<ReturnType<typeof listPendingApprovals>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPendingApprovals>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListPendingApprovalsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Cancels a pending approval request
 * @summary Cancel approval
 */
export const cancelApproval = (
  requestID: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<CancelApproval200>> => {
  return axios.default.delete(`/v1/human/pending/${requestID}`, options);
};

export const getCancelApprovalMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelApproval>>,
    TError,
    { requestID: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancelApproval>>,
  TError,
  { requestID: string },
  TContext
> => {
  const mutationKey = ["cancelApproval"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cancelApproval>>,
    { requestID: string }
  > = (props) => {
    const { requestID } = props ?? {};

    return cancelApproval(requestID, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CancelApprovalMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelApproval>>
>;

export type CancelApprovalMutationError =
  AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary Cancel approval
 */
export const useCancelApproval = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cancelApproval>>,
      TError,
      { requestID: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof cancelApproval>>,
  TError,
  { requestID: string },
  TContext
> => {
  const mutationOptions = getCancelApprovalMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Retrieves a specific pending approval request
 * @summary Get pending approval
 */
export const getPendingApproval = (
  requestID: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TmuxClientInternalTypesPendingApproval>> => {
  return axios.default.get(`/v1/human/pending/${requestID}`, options);
};

export const getGetPendingApprovalQueryKey = (requestID?: string) => {
  return [`/v1/human/pending/${requestID}`] as const;
};

export const getGetPendingApprovalQueryOptions = <
  TData = Awaited<ReturnType<typeof getPendingApproval>>,
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
>(
  requestID: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPendingApproval>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPendingApprovalQueryKey(requestID);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPendingApproval>>
  > = ({ signal }) =>
    getPendingApproval(requestID, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!requestID,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPendingApproval>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPendingApprovalQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPendingApproval>>
>;
export type GetPendingApprovalQueryError =
  AxiosError<TmuxClientInternalTypesAPIError>;

export function useGetPendingApproval<
  TData = Awaited<ReturnType<typeof getPendingApproval>>,
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
>(
  requestID: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPendingApproval>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPendingApproval>>,
          TError,
          Awaited<ReturnType<typeof getPendingApproval>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPendingApproval<
  TData = Awaited<ReturnType<typeof getPendingApproval>>,
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
>(
  requestID: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPendingApproval>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPendingApproval>>,
          TError,
          Awaited<ReturnType<typeof getPendingApproval>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPendingApproval<
  TData = Awaited<ReturnType<typeof getPendingApproval>>,
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
>(
  requestID: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPendingApproval>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get pending approval
 */

export function useGetPendingApproval<
  TData = Awaited<ReturnType<typeof getPendingApproval>>,
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
>(
  requestID: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPendingApproval>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPendingApprovalQueryOptions(requestID, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Responds to a pending approval request
 * @summary Respond to approval
 */
export const respondToApproval = (
  tmuxClientInternalTypesApproveRequest: TmuxClientInternalTypesApproveRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TmuxClientInternalTypesAskHumanResponse>> => {
  return axios.default.post(
    `/v1/human/respond`,
    tmuxClientInternalTypesApproveRequest,
    options,
  );
};

export const getRespondToApprovalMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof respondToApproval>>,
    TError,
    { data: TmuxClientInternalTypesApproveRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof respondToApproval>>,
  TError,
  { data: TmuxClientInternalTypesApproveRequest },
  TContext
> => {
  const mutationKey = ["respondToApproval"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof respondToApproval>>,
    { data: TmuxClientInternalTypesApproveRequest }
  > = (props) => {
    const { data } = props ?? {};

    return respondToApproval(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RespondToApprovalMutationResult = NonNullable<
  Awaited<ReturnType<typeof respondToApproval>>
>;
export type RespondToApprovalMutationBody =
  TmuxClientInternalTypesApproveRequest;
export type RespondToApprovalMutationError =
  AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary Respond to approval
 */
export const useRespondToApproval = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof respondToApproval>>,
      TError,
      { data: TmuxClientInternalTypesApproveRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof respondToApproval>>,
  TError,
  { data: TmuxClientInternalTypesApproveRequest },
  TContext
> => {
  const mutationOptions = getRespondToApprovalMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
