/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for interacting with tmux sessions, panes, and windows
 * OpenAPI spec version: 0.1-beta
 */
import * as zod from 'zod';


/**
 * Lists all execution plans
 * @summary List plans
 */
export const getApiV1PlanResponse = zod.object({
  "plans": zod.array(zod.object({
  "completed_at": zod.string().optional(),
  "created_at": zod.string().optional(),
  "current_step": zod.number().optional().describe('-1 if not started'),
  "description": zod.string().optional(),
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "status": zod.enum(['pending', 'in_progress', 'completed', 'failed', 'aborted']).optional(),
  "steps": zod.array(zod.object({
  "completed_at": zod.string().optional(),
  "description": zod.string().optional(),
  "error": zod.string().optional(),
  "index": zod.number().optional(),
  "result": zod.string().optional(),
  "started_at": zod.string().optional(),
  "status": zod.enum(['pending', 'active', 'completed', 'failed', 'skipped']).optional()
})).optional(),
  "updated_at": zod.string().optional()
})).optional()
})

/**
 * Deletes an execution plan
 * @summary Delete plan
 */
export const deleteApiV1PlanPlanIDParams = zod.object({
  "planID": zod.string().describe('Plan ID')
})

export const deleteApiV1PlanPlanIDResponse = zod.record(zod.string(), zod.unknown())

/**
 * Retrieves a specific execution plan
 * @summary Get plan
 */
export const getApiV1PlanPlanIDParams = zod.object({
  "planID": zod.string().describe('Plan ID')
})

export const getApiV1PlanPlanIDResponse = zod.object({
  "plan": zod.object({
  "completed_at": zod.string().optional(),
  "created_at": zod.string().optional(),
  "current_step": zod.number().optional().describe('-1 if not started'),
  "description": zod.string().optional(),
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "status": zod.enum(['pending', 'in_progress', 'completed', 'failed', 'aborted']).optional(),
  "steps": zod.array(zod.object({
  "completed_at": zod.string().optional(),
  "description": zod.string().optional(),
  "error": zod.string().optional(),
  "index": zod.number().optional(),
  "result": zod.string().optional(),
  "started_at": zod.string().optional(),
  "status": zod.enum(['pending', 'active', 'completed', 'failed', 'skipped']).optional()
})).optional(),
  "updated_at": zod.string().optional()
}).optional()
})

/**
 * Aborts an execution plan
 * @summary Abort plan
 */
export const postApiV1PlanPlanIDAbortParams = zod.object({
  "planID": zod.string().describe('Plan ID')
})

export const postApiV1PlanPlanIDAbortBody = zod.object({

})

export const postApiV1PlanPlanIDAbortResponse = zod.record(zod.string(), zod.unknown())

/**
 * Advances to the next step in a plan
 * @summary Advance plan step
 */
export const postApiV1PlanPlanIDAdvanceParams = zod.object({
  "planID": zod.string().describe('Plan ID')
})

export const postApiV1PlanPlanIDAdvanceBody = zod.object({

})

export const postApiV1PlanPlanIDAdvanceResponse = zod.record(zod.string(), zod.unknown())

/**
 * Creates a new execution plan
 * @summary Create plan
 */
export const postApiV1PlanCreateBody = zod.object({
  "description": zod.string().optional(),
  "name": zod.string().optional(),
  "steps": zod.array(zod.string()).optional().describe('Step descriptions')
})

export const postApiV1PlanCreateResponse = zod.object({
  "plan": zod.object({
  "completed_at": zod.string().optional(),
  "created_at": zod.string().optional(),
  "current_step": zod.number().optional().describe('-1 if not started'),
  "description": zod.string().optional(),
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "status": zod.enum(['pending', 'in_progress', 'completed', 'failed', 'aborted']).optional(),
  "steps": zod.array(zod.object({
  "completed_at": zod.string().optional(),
  "description": zod.string().optional(),
  "error": zod.string().optional(),
  "index": zod.number().optional(),
  "result": zod.string().optional(),
  "started_at": zod.string().optional(),
  "status": zod.enum(['pending', 'active', 'completed', 'failed', 'skipped']).optional()
})).optional(),
  "updated_at": zod.string().optional()
}).optional(),
  "plan_id": zod.string().optional()
})

/**
 * Updates an execution plan
 * @summary Update plan
 */
export const postApiV1PlanUpdateBody = zod.object({
  "error": zod.string().optional(),
  "plan_id": zod.string().optional(),
  "result": zod.string().optional(),
  "status": zod.enum(['pending', 'active', 'completed', 'failed', 'skipped']).optional(),
  "step_index": zod.number().optional()
})

export const postApiV1PlanUpdateResponse = zod.object({
  "plan": zod.object({
  "completed_at": zod.string().optional(),
  "created_at": zod.string().optional(),
  "current_step": zod.number().optional().describe('-1 if not started'),
  "description": zod.string().optional(),
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "status": zod.enum(['pending', 'in_progress', 'completed', 'failed', 'aborted']).optional(),
  "steps": zod.array(zod.object({
  "completed_at": zod.string().optional(),
  "description": zod.string().optional(),
  "error": zod.string().optional(),
  "index": zod.number().optional(),
  "result": zod.string().optional(),
  "started_at": zod.string().optional(),
  "status": zod.enum(['pending', 'active', 'completed', 'failed', 'skipped']).optional()
})).optional(),
  "updated_at": zod.string().optional()
}).optional(),
  "plan_id": zod.string().optional(),
  "updated": zod.boolean().optional()
})

