/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SandboxesIndexRouteImport } from './routes/sandboxes/index'
import { Route as AnsibleIndexRouteImport } from './routes/ansible/index'
import { Route as TmuxPageRouteImport } from './routes/tmux/page'
import { Route as SandboxesIdRouteImport } from './routes/sandboxes/$id'
import { Route as TmuxIdPageRouteImport } from './routes/tmux/[id]/page'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxesIndexRoute = SandboxesIndexRouteImport.update({
  id: '/sandboxes/',
  path: '/sandboxes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnsibleIndexRoute = AnsibleIndexRouteImport.update({
  id: '/ansible/',
  path: '/ansible/',
  getParentRoute: () => rootRouteImport,
} as any)
const TmuxPageRoute = TmuxPageRouteImport.update({
  id: '/tmux/page',
  path: '/tmux/page',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxesIdRoute = SandboxesIdRouteImport.update({
  id: '/sandboxes/$id',
  path: '/sandboxes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TmuxIdPageRoute = TmuxIdPageRouteImport.update({
  id: '/tmux/id/page',
  path: '/tmux/id/page',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sandboxes/$id': typeof SandboxesIdRoute
  '/tmux/page': typeof TmuxPageRoute
  '/ansible': typeof AnsibleIndexRoute
  '/sandboxes': typeof SandboxesIndexRoute
  '/tmux/id/page': typeof TmuxIdPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sandboxes/$id': typeof SandboxesIdRoute
  '/tmux/page': typeof TmuxPageRoute
  '/ansible': typeof AnsibleIndexRoute
  '/sandboxes': typeof SandboxesIndexRoute
  '/tmux/id/page': typeof TmuxIdPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sandboxes/$id': typeof SandboxesIdRoute
  '/tmux/page': typeof TmuxPageRoute
  '/ansible/': typeof AnsibleIndexRoute
  '/sandboxes/': typeof SandboxesIndexRoute
  '/tmux/id/page': typeof TmuxIdPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sandboxes/$id'
    | '/tmux/page'
    | '/ansible'
    | '/sandboxes'
    | '/tmux/id/page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sandboxes/$id'
    | '/tmux/page'
    | '/ansible'
    | '/sandboxes'
    | '/tmux/id/page'
  id:
    | '__root__'
    | '/'
    | '/sandboxes/$id'
    | '/tmux/page'
    | '/ansible/'
    | '/sandboxes/'
    | '/tmux/id/page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SandboxesIdRoute: typeof SandboxesIdRoute
  TmuxPageRoute: typeof TmuxPageRoute
  AnsibleIndexRoute: typeof AnsibleIndexRoute
  SandboxesIndexRoute: typeof SandboxesIndexRoute
  TmuxIdPageRoute: typeof TmuxIdPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandboxes/': {
      id: '/sandboxes/'
      path: '/sandboxes'
      fullPath: '/sandboxes'
      preLoaderRoute: typeof SandboxesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ansible/': {
      id: '/ansible/'
      path: '/ansible'
      fullPath: '/ansible'
      preLoaderRoute: typeof AnsibleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tmux/page': {
      id: '/tmux/page'
      path: '/tmux/page'
      fullPath: '/tmux/page'
      preLoaderRoute: typeof TmuxPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandboxes/$id': {
      id: '/sandboxes/$id'
      path: '/sandboxes/$id'
      fullPath: '/sandboxes/$id'
      preLoaderRoute: typeof SandboxesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tmux/id/page': {
      id: '/tmux/id/page'
      path: '/tmux/id/page'
      fullPath: '/tmux/id/page'
      preLoaderRoute: typeof TmuxIdPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SandboxesIdRoute: SandboxesIdRoute,
  TmuxPageRoute: TmuxPageRoute,
  AnsibleIndexRoute: AnsibleIndexRoute,
  SandboxesIndexRoute: SandboxesIndexRoute,
  TmuxIdPageRoute: TmuxIdPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
