/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * tmux-client API
 * API for managing tmux sessions and windows
 * OpenAPI spec version: 0.0.1-beta
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  CheckFileExists200,
  CheckFileExistsBody,
  GetFileHash200,
  GetFileHashBody,
  TmuxClientInternalTypesAPIError,
  TmuxClientInternalTypesCopyFileRequest,
  TmuxClientInternalTypesCopyFileResponse,
  TmuxClientInternalTypesDeleteFileRequest,
  TmuxClientInternalTypesDeleteFileResponse,
  TmuxClientInternalTypesEditFileRequest,
  TmuxClientInternalTypesEditFileResponse,
  TmuxClientInternalTypesListDirRequest,
  TmuxClientInternalTypesListDirResponse,
  TmuxClientInternalTypesReadFileRequest,
  TmuxClientInternalTypesReadFileResponse,
  TmuxClientInternalTypesWriteFileRequest,
  TmuxClientInternalTypesWriteFileResponse,
} from ".././model";

/**
 * Copies a file from source to destination
 * @summary Copy file
 */
export const copyFile = (
  tmuxClientInternalTypesCopyFileRequest: TmuxClientInternalTypesCopyFileRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TmuxClientInternalTypesCopyFileResponse>> => {
  return axios.default.post(
    `/v1/file/copy`,
    tmuxClientInternalTypesCopyFileRequest,
    options,
  );
};

export const getCopyFileMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof copyFile>>,
    TError,
    { data: TmuxClientInternalTypesCopyFileRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof copyFile>>,
  TError,
  { data: TmuxClientInternalTypesCopyFileRequest },
  TContext
> => {
  const mutationKey = ["copyFile"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof copyFile>>,
    { data: TmuxClientInternalTypesCopyFileRequest }
  > = (props) => {
    const { data } = props ?? {};

    return copyFile(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CopyFileMutationResult = NonNullable<
  Awaited<ReturnType<typeof copyFile>>
>;
export type CopyFileMutationBody = TmuxClientInternalTypesCopyFileRequest;
export type CopyFileMutationError = AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary Copy file
 */
export const useCopyFile = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof copyFile>>,
      TError,
      { data: TmuxClientInternalTypesCopyFileRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof copyFile>>,
  TError,
  { data: TmuxClientInternalTypesCopyFileRequest },
  TContext
> => {
  const mutationOptions = getCopyFileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Deletes a file or directory
 * @summary Delete file
 */
export const deleteFile = (
  tmuxClientInternalTypesDeleteFileRequest: TmuxClientInternalTypesDeleteFileRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TmuxClientInternalTypesDeleteFileResponse>> => {
  return axios.default.post(
    `/v1/file/delete`,
    tmuxClientInternalTypesDeleteFileRequest,
    options,
  );
};

export const getDeleteFileMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteFile>>,
    TError,
    { data: TmuxClientInternalTypesDeleteFileRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteFile>>,
  TError,
  { data: TmuxClientInternalTypesDeleteFileRequest },
  TContext
> => {
  const mutationKey = ["deleteFile"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteFile>>,
    { data: TmuxClientInternalTypesDeleteFileRequest }
  > = (props) => {
    const { data } = props ?? {};

    return deleteFile(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteFileMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteFile>>
>;
export type DeleteFileMutationBody = TmuxClientInternalTypesDeleteFileRequest;
export type DeleteFileMutationError =
  AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary Delete file
 */
export const useDeleteFile = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteFile>>,
      TError,
      { data: TmuxClientInternalTypesDeleteFileRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteFile>>,
  TError,
  { data: TmuxClientInternalTypesDeleteFileRequest },
  TContext
> => {
  const mutationOptions = getDeleteFileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Edits the content of a file
 * @summary Edit file
 */
export const editFile = (
  tmuxClientInternalTypesEditFileRequest: TmuxClientInternalTypesEditFileRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TmuxClientInternalTypesEditFileResponse>> => {
  return axios.default.post(
    `/v1/file/edit`,
    tmuxClientInternalTypesEditFileRequest,
    options,
  );
};

export const getEditFileMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof editFile>>,
    TError,
    { data: TmuxClientInternalTypesEditFileRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof editFile>>,
  TError,
  { data: TmuxClientInternalTypesEditFileRequest },
  TContext
> => {
  const mutationKey = ["editFile"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof editFile>>,
    { data: TmuxClientInternalTypesEditFileRequest }
  > = (props) => {
    const { data } = props ?? {};

    return editFile(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EditFileMutationResult = NonNullable<
  Awaited<ReturnType<typeof editFile>>
>;
export type EditFileMutationBody = TmuxClientInternalTypesEditFileRequest;
export type EditFileMutationError = AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary Edit file
 */
export const useEditFile = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof editFile>>,
      TError,
      { data: TmuxClientInternalTypesEditFileRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof editFile>>,
  TError,
  { data: TmuxClientInternalTypesEditFileRequest },
  TContext
> => {
  const mutationOptions = getEditFileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Checks if a file or directory exists
 * @summary Check if file exists
 */
export const checkFileExists = (
  checkFileExistsBody: CheckFileExistsBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<CheckFileExists200>> => {
  return axios.default.post(`/v1/file/exists`, checkFileExistsBody, options);
};

export const getCheckFileExistsMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof checkFileExists>>,
    TError,
    { data: CheckFileExistsBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof checkFileExists>>,
  TError,
  { data: CheckFileExistsBody },
  TContext
> => {
  const mutationKey = ["checkFileExists"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof checkFileExists>>,
    { data: CheckFileExistsBody }
  > = (props) => {
    const { data } = props ?? {};

    return checkFileExists(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CheckFileExistsMutationResult = NonNullable<
  Awaited<ReturnType<typeof checkFileExists>>
>;
export type CheckFileExistsMutationBody = CheckFileExistsBody;
export type CheckFileExistsMutationError =
  AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary Check if file exists
 */
export const useCheckFileExists = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof checkFileExists>>,
      TError,
      { data: CheckFileExistsBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof checkFileExists>>,
  TError,
  { data: CheckFileExistsBody },
  TContext
> => {
  const mutationOptions = getCheckFileExistsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Computes the SHA256 hash of a file
 * @summary Get file hash
 */
export const getFileHash = (
  getFileHashBody: GetFileHashBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetFileHash200>> => {
  return axios.default.post(`/v1/file/hash`, getFileHashBody, options);
};

export const getGetFileHashMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getFileHash>>,
    TError,
    { data: GetFileHashBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getFileHash>>,
  TError,
  { data: GetFileHashBody },
  TContext
> => {
  const mutationKey = ["getFileHash"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getFileHash>>,
    { data: GetFileHashBody }
  > = (props) => {
    const { data } = props ?? {};

    return getFileHash(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetFileHashMutationResult = NonNullable<
  Awaited<ReturnType<typeof getFileHash>>
>;
export type GetFileHashMutationBody = GetFileHashBody;
export type GetFileHashMutationError =
  AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary Get file hash
 */
export const useGetFileHash = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof getFileHash>>,
      TError,
      { data: GetFileHashBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof getFileHash>>,
  TError,
  { data: GetFileHashBody },
  TContext
> => {
  const mutationOptions = getGetFileHashMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Lists the contents of a directory
 * @summary List directory contents
 */
export const listDirectory = (
  tmuxClientInternalTypesListDirRequest: TmuxClientInternalTypesListDirRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TmuxClientInternalTypesListDirResponse>> => {
  return axios.default.post(
    `/v1/file/list`,
    tmuxClientInternalTypesListDirRequest,
    options,
  );
};

export const getListDirectoryMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof listDirectory>>,
    TError,
    { data: TmuxClientInternalTypesListDirRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof listDirectory>>,
  TError,
  { data: TmuxClientInternalTypesListDirRequest },
  TContext
> => {
  const mutationKey = ["listDirectory"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof listDirectory>>,
    { data: TmuxClientInternalTypesListDirRequest }
  > = (props) => {
    const { data } = props ?? {};

    return listDirectory(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ListDirectoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof listDirectory>>
>;
export type ListDirectoryMutationBody = TmuxClientInternalTypesListDirRequest;
export type ListDirectoryMutationError =
  AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary List directory contents
 */
export const useListDirectory = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof listDirectory>>,
      TError,
      { data: TmuxClientInternalTypesListDirRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof listDirectory>>,
  TError,
  { data: TmuxClientInternalTypesListDirRequest },
  TContext
> => {
  const mutationOptions = getListDirectoryMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Reads the content of a file
 * @summary Read file
 */
export const readFile = (
  tmuxClientInternalTypesReadFileRequest: TmuxClientInternalTypesReadFileRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TmuxClientInternalTypesReadFileResponse>> => {
  return axios.default.post(
    `/v1/file/read`,
    tmuxClientInternalTypesReadFileRequest,
    options,
  );
};

export const getReadFileMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof readFile>>,
    TError,
    { data: TmuxClientInternalTypesReadFileRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof readFile>>,
  TError,
  { data: TmuxClientInternalTypesReadFileRequest },
  TContext
> => {
  const mutationKey = ["readFile"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof readFile>>,
    { data: TmuxClientInternalTypesReadFileRequest }
  > = (props) => {
    const { data } = props ?? {};

    return readFile(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReadFileMutationResult = NonNullable<
  Awaited<ReturnType<typeof readFile>>
>;
export type ReadFileMutationBody = TmuxClientInternalTypesReadFileRequest;
export type ReadFileMutationError = AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary Read file
 */
export const useReadFile = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof readFile>>,
      TError,
      { data: TmuxClientInternalTypesReadFileRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof readFile>>,
  TError,
  { data: TmuxClientInternalTypesReadFileRequest },
  TContext
> => {
  const mutationOptions = getReadFileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Writes content to a file
 * @summary Write file
 */
export const writeFile = (
  tmuxClientInternalTypesWriteFileRequest: TmuxClientInternalTypesWriteFileRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TmuxClientInternalTypesWriteFileResponse>> => {
  return axios.default.post(
    `/v1/file/write`,
    tmuxClientInternalTypesWriteFileRequest,
    options,
  );
};

export const getWriteFileMutationOptions = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof writeFile>>,
    TError,
    { data: TmuxClientInternalTypesWriteFileRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof writeFile>>,
  TError,
  { data: TmuxClientInternalTypesWriteFileRequest },
  TContext
> => {
  const mutationKey = ["writeFile"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof writeFile>>,
    { data: TmuxClientInternalTypesWriteFileRequest }
  > = (props) => {
    const { data } = props ?? {};

    return writeFile(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type WriteFileMutationResult = NonNullable<
  Awaited<ReturnType<typeof writeFile>>
>;
export type WriteFileMutationBody = TmuxClientInternalTypesWriteFileRequest;
export type WriteFileMutationError =
  AxiosError<TmuxClientInternalTypesAPIError>;

/**
 * @summary Write file
 */
export const useWriteFile = <
  TError = AxiosError<TmuxClientInternalTypesAPIError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof writeFile>>,
      TError,
      { data: TmuxClientInternalTypesWriteFileRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof writeFile>>,
  TError,
  { data: TmuxClientInternalTypesWriteFileRequest },
  TContext
> => {
  const mutationOptions = getWriteFileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
